@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.data
	.align	2, 0
	.type	 sccsid,object
	.size	 sccsid,35
sccsid:
	.ascii	"@(#)unctrl.c\t8.1 (Berkeley) 6/4/93\000"
	.globl	__unctrl
	.section .rodata
	.align	2, 0
	.type	 __unctrl,object
	.size	 __unctrl,1024
__unctrl:
	.word	.LC0
	.word	.LC1
	.word	.LC2
	.word	.LC3
	.word	.LC4
	.word	.LC5
	.word	.LC6
	.word	.LC7
	.word	.LC8
	.word	.LC9
	.word	.LC10
	.word	.LC11
	.word	.LC12
	.word	.LC13
	.word	.LC14
	.word	.LC15
	.word	.LC16
	.word	.LC17
	.word	.LC18
	.word	.LC19
	.word	.LC20
	.word	.LC21
	.word	.LC22
	.word	.LC23
	.word	.LC24
	.word	.LC25
	.word	.LC26
	.word	.LC27
	.word	.LC28
	.word	.LC29
	.word	.LC30
	.word	.LC31
	.word	.LC32
	.word	.LC33
	.word	.LC34
	.word	.LC35
	.word	.LC36
	.word	.LC37
	.word	.LC38
	.word	.LC39
	.word	.LC40
	.word	.LC41
	.word	.LC42
	.word	.LC43
	.word	.LC44
	.word	.LC45
	.word	.LC46
	.word	.LC47
	.word	.LC48
	.word	.LC49
	.word	.LC50
	.word	.LC51
	.word	.LC52
	.word	.LC53
	.word	.LC54
	.word	.LC55
	.word	.LC56
	.word	.LC57
	.word	.LC58
	.word	.LC59
	.word	.LC60
	.word	.LC61
	.word	.LC62
	.word	.LC63
	.word	.LC64
	.word	.LC65
	.word	.LC66
	.word	.LC67
	.word	.LC68
	.word	.LC69
	.word	.LC70
	.word	.LC71
	.word	.LC72
	.word	.LC73
	.word	.LC74
	.word	.LC75
	.word	.LC76
	.word	.LC77
	.word	.LC78
	.word	.LC79
	.word	.LC80
	.word	.LC81
	.word	.LC82
	.word	.LC83
	.word	.LC84
	.word	.LC85
	.word	.LC86
	.word	.LC87
	.word	.LC88
	.word	.LC89
	.word	.LC90
	.word	.LC91
	.word	.LC92
	.word	.LC93
	.word	.LC94
	.word	.LC95
	.word	.LC96
	.word	.LC97
	.word	.LC98
	.word	.LC99
	.word	.LC100
	.word	.LC101
	.word	.LC102
	.word	.LC103
	.word	.LC104
	.word	.LC105
	.word	.LC106
	.word	.LC107
	.word	.LC108
	.word	.LC109
	.word	.LC110
	.word	.LC111
	.word	.LC112
	.word	.LC113
	.word	.LC114
	.word	.LC115
	.word	.LC116
	.word	.LC117
	.word	.LC118
	.word	.LC119
	.word	.LC120
	.word	.LC121
	.word	.LC122
	.word	.LC123
	.word	.LC124
	.word	.LC125
	.word	.LC126
	.word	.LC127
	.word	.LC128
	.word	.LC129
	.word	.LC130
	.word	.LC131
	.word	.LC132
	.word	.LC133
	.word	.LC134
	.word	.LC135
	.word	.LC136
	.word	.LC137
	.word	.LC138
	.word	.LC139
	.word	.LC140
	.word	.LC141
	.word	.LC142
	.word	.LC143
	.word	.LC144
	.word	.LC145
	.word	.LC146
	.word	.LC147
	.word	.LC148
	.word	.LC149
	.word	.LC150
	.word	.LC151
	.word	.LC152
	.word	.LC153
	.word	.LC154
	.word	.LC155
	.word	.LC156
	.word	.LC157
	.word	.LC158
	.word	.LC159
	.word	.LC160
	.word	.LC161
	.word	.LC162
	.word	.LC163
	.word	.LC164
	.word	.LC165
	.word	.LC166
	.word	.LC167
	.word	.LC168
	.word	.LC169
	.word	.LC170
	.word	.LC171
	.word	.LC172
	.word	.LC173
	.word	.LC174
	.word	.LC175
	.word	.LC176
	.word	.LC177
	.word	.LC178
	.word	.LC179
	.word	.LC180
	.word	.LC181
	.word	.LC182
	.word	.LC183
	.word	.LC184
	.word	.LC185
	.word	.LC186
	.word	.LC187
	.word	.LC188
	.word	.LC189
	.word	.LC190
	.word	.LC191
	.word	.LC192
	.word	.LC193
	.word	.LC194
	.word	.LC195
	.word	.LC196
	.word	.LC197
	.word	.LC198
	.word	.LC199
	.word	.LC200
	.word	.LC201
	.word	.LC202
	.word	.LC203
	.word	.LC204
	.word	.LC205
	.word	.LC206
	.word	.LC207
	.word	.LC208
	.word	.LC209
	.word	.LC210
	.word	.LC211
	.word	.LC212
	.word	.LC213
	.word	.LC214
	.word	.LC215
	.word	.LC216
	.word	.LC217
	.word	.LC218
	.word	.LC219
	.word	.LC220
	.word	.LC221
	.word	.LC222
	.word	.LC223
	.word	.LC224
	.word	.LC225
	.word	.LC226
	.word	.LC227
	.word	.LC228
	.word	.LC229
	.word	.LC230
	.word	.LC231
	.word	.LC232
	.word	.LC233
	.word	.LC234
	.word	.LC235
	.word	.LC236
	.word	.LC237
	.word	.LC238
	.word	.LC239
	.word	.LC240
	.word	.LC241
	.word	.LC242
	.word	.LC243
	.word	.LC244
	.word	.LC245
	.word	.LC246
	.word	.LC247
	.word	.LC248
	.word	.LC249
	.word	.LC250
	.word	.LC251
	.word	.LC252
	.word	.LC253
	.word	.LC254
	.word	.LC255
	.align	2, 0
.LC255:
	.ascii	"0xff\000"
	.align	2, 0
.LC254:
	.ascii	"0xfe\000"
	.align	2, 0
.LC253:
	.ascii	"0xfd\000"
	.align	2, 0
.LC252:
	.ascii	"0xfc\000"
	.align	2, 0
.LC251:
	.ascii	"0xfb\000"
	.align	2, 0
.LC250:
	.ascii	"0xfa\000"
	.align	2, 0
.LC249:
	.ascii	"0xf9\000"
	.align	2, 0
.LC248:
	.ascii	"0xf8\000"
	.align	2, 0
.LC247:
	.ascii	"0xf7\000"
	.align	2, 0
.LC246:
	.ascii	"0xf6\000"
	.align	2, 0
.LC245:
	.ascii	"0xf5\000"
	.align	2, 0
.LC244:
	.ascii	"0xf4\000"
	.align	2, 0
.LC243:
	.ascii	"0xf3\000"
	.align	2, 0
.LC242:
	.ascii	"0xf2\000"
	.align	2, 0
.LC241:
	.ascii	"0xf1\000"
	.align	2, 0
.LC240:
	.ascii	"0xf0\000"
	.align	2, 0
.LC239:
	.ascii	"0xef\000"
	.align	2, 0
.LC238:
	.ascii	"0xee\000"
	.align	2, 0
.LC237:
	.ascii	"0xed\000"
	.align	2, 0
.LC236:
	.ascii	"0xec\000"
	.align	2, 0
.LC235:
	.ascii	"0xeb\000"
	.align	2, 0
.LC234:
	.ascii	"0xea\000"
	.align	2, 0
.LC233:
	.ascii	"0xe9\000"
	.align	2, 0
.LC232:
	.ascii	"0xe8\000"
	.align	2, 0
.LC231:
	.ascii	"0xe7\000"
	.align	2, 0
.LC230:
	.ascii	"0xe6\000"
	.align	2, 0
.LC229:
	.ascii	"0xe5\000"
	.align	2, 0
.LC228:
	.ascii	"0xe4\000"
	.align	2, 0
.LC227:
	.ascii	"0xe3\000"
	.align	2, 0
.LC226:
	.ascii	"0xe2\000"
	.align	2, 0
.LC225:
	.ascii	"0xe1\000"
	.align	2, 0
.LC224:
	.ascii	"0xe0\000"
	.align	2, 0
.LC223:
	.ascii	"0xdf\000"
	.align	2, 0
.LC222:
	.ascii	"0xde\000"
	.align	2, 0
.LC221:
	.ascii	"0xdd\000"
	.align	2, 0
.LC220:
	.ascii	"0xdc\000"
	.align	2, 0
.LC219:
	.ascii	"0xdb\000"
	.align	2, 0
.LC218:
	.ascii	"0xda\000"
	.align	2, 0
.LC217:
	.ascii	"0xd9\000"
	.align	2, 0
.LC216:
	.ascii	"0xd8\000"
	.align	2, 0
.LC215:
	.ascii	"0xd7\000"
	.align	2, 0
.LC214:
	.ascii	"0xd6\000"
	.align	2, 0
.LC213:
	.ascii	"0xd5\000"
	.align	2, 0
.LC212:
	.ascii	"0xd4\000"
	.align	2, 0
.LC211:
	.ascii	"0xd3\000"
	.align	2, 0
.LC210:
	.ascii	"0xd2\000"
	.align	2, 0
.LC209:
	.ascii	"0xd1\000"
	.align	2, 0
.LC208:
	.ascii	"0xd0\000"
	.align	2, 0
.LC207:
	.ascii	"0xcf\000"
	.align	2, 0
.LC206:
	.ascii	"0xce\000"
	.align	2, 0
.LC205:
	.ascii	"0xcd\000"
	.align	2, 0
.LC204:
	.ascii	"0xcc\000"
	.align	2, 0
.LC203:
	.ascii	"0xcb\000"
	.align	2, 0
.LC202:
	.ascii	"0xca\000"
	.align	2, 0
.LC201:
	.ascii	"0xc9\000"
	.align	2, 0
.LC200:
	.ascii	"0xc8\000"
	.align	2, 0
.LC199:
	.ascii	"0xc7\000"
	.align	2, 0
.LC198:
	.ascii	"0xc6\000"
	.align	2, 0
.LC197:
	.ascii	"0xc5\000"
	.align	2, 0
.LC196:
	.ascii	"0xc4\000"
	.align	2, 0
.LC195:
	.ascii	"0xc3\000"
	.align	2, 0
.LC194:
	.ascii	"0xc2\000"
	.align	2, 0
.LC193:
	.ascii	"0xc1\000"
	.align	2, 0
.LC192:
	.ascii	"0xc0\000"
	.align	2, 0
.LC191:
	.ascii	"0xbf\000"
	.align	2, 0
.LC190:
	.ascii	"0xbe\000"
	.align	2, 0
.LC189:
	.ascii	"0xbd\000"
	.align	2, 0
.LC188:
	.ascii	"0xbc\000"
	.align	2, 0
.LC187:
	.ascii	"0xbb\000"
	.align	2, 0
.LC186:
	.ascii	"0xba\000"
	.align	2, 0
.LC185:
	.ascii	"0xb9\000"
	.align	2, 0
.LC184:
	.ascii	"0xb8\000"
	.align	2, 0
.LC183:
	.ascii	"0xb7\000"
	.align	2, 0
.LC182:
	.ascii	"0xb6\000"
	.align	2, 0
.LC181:
	.ascii	"0xb5\000"
	.align	2, 0
.LC180:
	.ascii	"0xb4\000"
	.align	2, 0
.LC179:
	.ascii	"0xb3\000"
	.align	2, 0
.LC178:
	.ascii	"0xb2\000"
	.align	2, 0
.LC177:
	.ascii	"0xb1\000"
	.align	2, 0
.LC176:
	.ascii	"0xb0\000"
	.align	2, 0
.LC175:
	.ascii	"0xaf\000"
	.align	2, 0
.LC174:
	.ascii	"0xae\000"
	.align	2, 0
.LC173:
	.ascii	"0xad\000"
	.align	2, 0
.LC172:
	.ascii	"0xac\000"
	.align	2, 0
.LC171:
	.ascii	"0xab\000"
	.align	2, 0
.LC170:
	.ascii	"0xaa\000"
	.align	2, 0
.LC169:
	.ascii	"0xa9\000"
	.align	2, 0
.LC168:
	.ascii	"0xa8\000"
	.align	2, 0
.LC167:
	.ascii	"0xa7\000"
	.align	2, 0
.LC166:
	.ascii	"0xa6\000"
	.align	2, 0
.LC165:
	.ascii	"0xa5\000"
	.align	2, 0
.LC164:
	.ascii	"0xa4\000"
	.align	2, 0
.LC163:
	.ascii	"0xa3\000"
	.align	2, 0
.LC162:
	.ascii	"0xa2\000"
	.align	2, 0
.LC161:
	.ascii	"0xa1\000"
	.align	2, 0
.LC160:
	.ascii	"0xa0\000"
	.align	2, 0
.LC159:
	.ascii	"0x9f\000"
	.align	2, 0
.LC158:
	.ascii	"0x9e\000"
	.align	2, 0
.LC157:
	.ascii	"0x9d\000"
	.align	2, 0
.LC156:
	.ascii	"0x9c\000"
	.align	2, 0
.LC155:
	.ascii	"0x9b\000"
	.align	2, 0
.LC154:
	.ascii	"0x9a\000"
	.align	2, 0
.LC153:
	.ascii	"0x99\000"
	.align	2, 0
.LC152:
	.ascii	"0x98\000"
	.align	2, 0
.LC151:
	.ascii	"0x97\000"
	.align	2, 0
.LC150:
	.ascii	"0x96\000"
	.align	2, 0
.LC149:
	.ascii	"0x95\000"
	.align	2, 0
.LC148:
	.ascii	"0x94\000"
	.align	2, 0
.LC147:
	.ascii	"0x93\000"
	.align	2, 0
.LC146:
	.ascii	"0x92\000"
	.align	2, 0
.LC145:
	.ascii	"0x91\000"
	.align	2, 0
.LC144:
	.ascii	"0x90\000"
	.align	2, 0
.LC143:
	.ascii	"0x8f\000"
	.align	2, 0
.LC142:
	.ascii	"0x8e\000"
	.align	2, 0
.LC141:
	.ascii	"0x8d\000"
	.align	2, 0
.LC140:
	.ascii	"0x8c\000"
	.align	2, 0
.LC139:
	.ascii	"0x8b\000"
	.align	2, 0
.LC138:
	.ascii	"0x8a\000"
	.align	2, 0
.LC137:
	.ascii	"0x89\000"
	.align	2, 0
.LC136:
	.ascii	"0x88\000"
	.align	2, 0
.LC135:
	.ascii	"0x87\000"
	.align	2, 0
.LC134:
	.ascii	"0x86\000"
	.align	2, 0
.LC133:
	.ascii	"0x85\000"
	.align	2, 0
.LC132:
	.ascii	"0x84\000"
	.align	2, 0
.LC131:
	.ascii	"0x83\000"
	.align	2, 0
.LC130:
	.ascii	"0x82\000"
	.align	2, 0
.LC129:
	.ascii	"0x81\000"
	.align	2, 0
.LC128:
	.ascii	"0x80\000"
	.align	2, 0
.LC127:
	.ascii	"^?\000"
	.align	2, 0
.LC126:
	.ascii	"~\000"
	.align	2, 0
.LC125:
	.ascii	"}\000"
	.align	2, 0
.LC124:
	.ascii	"|\000"
	.align	2, 0
.LC123:
	.ascii	"{\000"
	.align	2, 0
.LC122:
	.ascii	"z\000"
	.align	2, 0
.LC121:
	.ascii	"y\000"
	.align	2, 0
.LC120:
	.ascii	"x\000"
	.align	2, 0
.LC119:
	.ascii	"w\000"
	.align	2, 0
.LC118:
	.ascii	"v\000"
	.align	2, 0
.LC117:
	.ascii	"u\000"
	.align	2, 0
.LC116:
	.ascii	"t\000"
	.align	2, 0
.LC115:
	.ascii	"s\000"
	.align	2, 0
.LC114:
	.ascii	"r\000"
	.align	2, 0
.LC113:
	.ascii	"q\000"
	.align	2, 0
.LC112:
	.ascii	"p\000"
	.align	2, 0
.LC111:
	.ascii	"o\000"
	.align	2, 0
.LC110:
	.ascii	"n\000"
	.align	2, 0
.LC109:
	.ascii	"m\000"
	.align	2, 0
.LC108:
	.ascii	"l\000"
	.align	2, 0
.LC107:
	.ascii	"k\000"
	.align	2, 0
.LC106:
	.ascii	"j\000"
	.align	2, 0
.LC105:
	.ascii	"i\000"
	.align	2, 0
.LC104:
	.ascii	"h\000"
	.align	2, 0
.LC103:
	.ascii	"g\000"
	.align	2, 0
.LC102:
	.ascii	"f\000"
	.align	2, 0
.LC101:
	.ascii	"e\000"
	.align	2, 0
.LC100:
	.ascii	"d\000"
	.align	2, 0
.LC99:
	.ascii	"c\000"
	.align	2, 0
.LC98:
	.ascii	"b\000"
	.align	2, 0
.LC97:
	.ascii	"a\000"
	.align	2, 0
.LC96:
	.ascii	"`\000"
	.align	2, 0
.LC95:
	.ascii	"_\000"
	.align	2, 0
.LC94:
	.ascii	"^\000"
	.align	2, 0
.LC93:
	.ascii	"]\000"
	.align	2, 0
.LC92:
	.ascii	"\\\000"
	.align	2, 0
.LC91:
	.ascii	"[\000"
	.align	2, 0
.LC90:
	.ascii	"Z\000"
	.align	2, 0
.LC89:
	.ascii	"Y\000"
	.align	2, 0
.LC88:
	.ascii	"X\000"
	.align	2, 0
.LC87:
	.ascii	"W\000"
	.align	2, 0
.LC86:
	.ascii	"V\000"
	.align	2, 0
.LC85:
	.ascii	"U\000"
	.align	2, 0
.LC84:
	.ascii	"T\000"
	.align	2, 0
.LC83:
	.ascii	"S\000"
	.align	2, 0
.LC82:
	.ascii	"R\000"
	.align	2, 0
.LC81:
	.ascii	"Q\000"
	.align	2, 0
.LC80:
	.ascii	"P\000"
	.align	2, 0
.LC79:
	.ascii	"O\000"
	.align	2, 0
.LC78:
	.ascii	"N\000"
	.align	2, 0
.LC77:
	.ascii	"M\000"
	.align	2, 0
.LC76:
	.ascii	"L\000"
	.align	2, 0
.LC75:
	.ascii	"K\000"
	.align	2, 0
.LC74:
	.ascii	"J\000"
	.align	2, 0
.LC73:
	.ascii	"I\000"
	.align	2, 0
.LC72:
	.ascii	"H\000"
	.align	2, 0
.LC71:
	.ascii	"G\000"
	.align	2, 0
.LC70:
	.ascii	"F\000"
	.align	2, 0
.LC69:
	.ascii	"E\000"
	.align	2, 0
.LC68:
	.ascii	"D\000"
	.align	2, 0
.LC67:
	.ascii	"C\000"
	.align	2, 0
.LC66:
	.ascii	"B\000"
	.align	2, 0
.LC65:
	.ascii	"A\000"
	.align	2, 0
.LC64:
	.ascii	"@\000"
	.align	2, 0
.LC63:
	.ascii	"?\000"
	.align	2, 0
.LC62:
	.ascii	">\000"
	.align	2, 0
.LC61:
	.ascii	"=\000"
	.align	2, 0
.LC60:
	.ascii	"<\000"
	.align	2, 0
.LC59:
	.ascii	";\000"
	.align	2, 0
.LC58:
	.ascii	":\000"
	.align	2, 0
.LC57:
	.ascii	"9\000"
	.align	2, 0
.LC56:
	.ascii	"8\000"
	.align	2, 0
.LC55:
	.ascii	"7\000"
	.align	2, 0
.LC54:
	.ascii	"6\000"
	.align	2, 0
.LC53:
	.ascii	"5\000"
	.align	2, 0
.LC52:
	.ascii	"4\000"
	.align	2, 0
.LC51:
	.ascii	"3\000"
	.align	2, 0
.LC50:
	.ascii	"2\000"
	.align	2, 0
.LC49:
	.ascii	"1\000"
	.align	2, 0
.LC48:
	.ascii	"0\000"
	.align	2, 0
.LC47:
	.ascii	"/\000"
	.align	2, 0
.LC46:
	.ascii	".\000"
	.align	2, 0
.LC45:
	.ascii	"-\000"
	.align	2, 0
.LC44:
	.ascii	",\000"
	.align	2, 0
.LC43:
	.ascii	"+\000"
	.align	2, 0
.LC42:
	.ascii	"*\000"
	.align	2, 0
.LC41:
	.ascii	")\000"
	.align	2, 0
.LC40:
	.ascii	"(\000"
	.align	2, 0
.LC39:
	.ascii	"'\000"
	.align	2, 0
.LC38:
	.ascii	"&\000"
	.align	2, 0
.LC37:
	.ascii	"%\000"
	.align	2, 0
.LC36:
	.ascii	"$\000"
	.align	2, 0
.LC35:
	.ascii	"#\000"
	.align	2, 0
.LC34:
	.ascii	"\"\000"
	.align	2, 0
.LC33:
	.ascii	"!\000"
	.align	2, 0
.LC32:
	.ascii	" \000"
	.align	2, 0
.LC31:
	.ascii	"^_\000"
	.align	2, 0
.LC30:
	.ascii	"^~\000"
	.align	2, 0
.LC29:
	.ascii	"^]\000"
	.align	2, 0
.LC28:
	.ascii	"^\\\000"
	.align	2, 0
.LC27:
	.ascii	"^[\000"
	.align	2, 0
.LC26:
	.ascii	"^Z\000"
	.align	2, 0
.LC25:
	.ascii	"^Y\000"
	.align	2, 0
.LC24:
	.ascii	"^X\000"
	.align	2, 0
.LC23:
	.ascii	"^W\000"
	.align	2, 0
.LC22:
	.ascii	"^V\000"
	.align	2, 0
.LC21:
	.ascii	"^U\000"
	.align	2, 0
.LC20:
	.ascii	"^T\000"
	.align	2, 0
.LC19:
	.ascii	"^S\000"
	.align	2, 0
.LC18:
	.ascii	"^R\000"
	.align	2, 0
.LC17:
	.ascii	"^Q\000"
	.align	2, 0
.LC16:
	.ascii	"^P\000"
	.align	2, 0
.LC15:
	.ascii	"^O\000"
	.align	2, 0
.LC14:
	.ascii	"^N\000"
	.align	2, 0
.LC13:
	.ascii	"^M\000"
	.align	2, 0
.LC12:
	.ascii	"^L\000"
	.align	2, 0
.LC11:
	.ascii	"^K\000"
	.align	2, 0
.LC10:
	.ascii	"^J\000"
	.align	2, 0
.LC9:
	.ascii	"^I\000"
	.align	2, 0
.LC8:
	.ascii	"^H\000"
	.align	2, 0
.LC7:
	.ascii	"^G\000"
	.align	2, 0
.LC6:
	.ascii	"^F\000"
	.align	2, 0
.LC5:
	.ascii	"^E\000"
	.align	2, 0
.LC4:
	.ascii	"^D\000"
	.align	2, 0
.LC3:
	.ascii	"^C\000"
	.align	2, 0
.LC2:
	.ascii	"^B\000"
	.align	2, 0
.LC1:
	.ascii	"^A\000"
	.align	2, 0
.LC0:
	.ascii	"^@\000"
	.globl	__unctrllen
	.type	 __unctrllen,object
	.size	 __unctrllen,256
__unctrllen:
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	2
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	1
	.byte	2
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
	.byte	4
.text
	.align	2, 0
