@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	copysign
	.type	 copysign,function
	.thumb_func
copysign:
	push	{r4, r5, r6, r7, lr}
	add	r7, r1, #0
	add	r6, r0, #0
	add	r5, r7, #0
	add	r4, r6, #0
	ldr	r1, .L18
	and	r1, r1, r6
	mov	r0, #128
	lsl	r0, r0, #24
	and	r0, r0, r2
	add	r4, r1, #0
	orr	r4, r4, r0
	add	r7, r5, #0
	add	r6, r4, #0
	add	r1, r7, #0
	add	r0, r6, #0
	pop	{r4, r5, r6, r7, pc}
.L19:
	.align	2, 0
.L18:
	.word	2147483647
.Lfe1:
	.size	 copysign,.Lfe1-copysign
.text
	.align	2, 0
