@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	__infinity
	.section .rodata
	.align	2, 0
	.type	 __infinity,object
	.size	 __infinity,8
__infinity:
	.word	2146435072
	.word	0
.text
	.align	2, 0
