@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	isnan
	.type	 isnan,function
	.thumb_func
isnan:
	ldr	r3, .L8
	and	r3, r3, r0
	neg	r2, r1
	orr	r2, r2, r1
	lsr	r2, r2, #31
	orr	r3, r3, r2
	ldr	r0, .L8+4
	sub	r3, r0, r3
	lsr	r3, r3, #31
	add	r0, r3, #0
	bx	lr
.L9:
	.align	2, 0
.L8:
	.word	2147483647
	.word	2146435072
.Lfe1:
	.size	 isnan,.Lfe1-isnan
.text
	.align	2, 0
