@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	ldexp
	.type	 ldexp,function
	.thumb_func
ldexp:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	add	r5, r1, #0
	add	r4, r0, #0
	mov	r8, r2
	bl	finite
	cmp	r0, #0
	beq	.L5	@cond_branch
	ldr	r7, .L8+4		@ created by thumb_load_double_from_address
	ldr	r6, .L8		@ created by thumb_load_double_from_address
	add	r1, r5, #0
	add	r0, r4, #0
	add	r3, r7, #0
	add	r2, r6, #0
	bl	__eqdf2
	cmp	r0, #0
	beq	.L5	@cond_branch
	add	r1, r5, #0
	add	r0, r4, #0
	mov	r2, r8
	bl	scalbn
	add	r5, r1, #0
	add	r4, r0, #0
	bl	finite
	cmp	r0, #0
	beq	.L6	@cond_branch
	add	r1, r5, #0
	add	r0, r4, #0
	add	r3, r7, #0
	add	r2, r6, #0
	bl	__eqdf2
	cmp	r0, #0
	bne	.L5	@cond_branch
.L6:
	bl	__errno
	mov	r1, #34
	str	r1, [r0]
.L5:
	add	r1, r5, #0
	add	r0, r4, #0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7, pc}
.L9:
	.align	2, 0
.L8:
	.long 0x0, 0x0	@ double 0.00000000000000000000e0
.Lfe1:
	.size	 ldexp,.Lfe1-ldexp
.text
	.align	2, 0
