@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	copysignf
	.type	 copysignf,function
	.thumb_func
copysignf:
	ldr	r2, .L18
	and	r2, r2, r0
	mov	r0, #128
	lsl	r0, r0, #24
	and	r0, r0, r1
	orr	r0, r0, r2
	bx	lr
.L19:
	.align	2, 0
.L18:
	.word	2147483647
.Lfe1:
	.size	 copysignf,.Lfe1-copysignf
.text
	.align	2, 0
