@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
	.type	 two25,object
	.size	 two25,4
two25:
	.word 0x4c000000	@ float 3.35544320000000000000e7
.text
	.align	2, 0
	.globl	frexpf
	.type	 frexpf,function
	.thumb_func
frexpf:
	push	{r4, r5, lr}
	add	r2, r0, #0
	add	r4, r1, #0
	add	r3, r2, #0
	ldr	r5, .L23
	add	r1, r3, #0
	and	r1, r1, r5
	mov	r0, #0
	str	r0, [r4]
	ldr	r0, .L23+4
	cmp	r1, r0
	bgt	.L22	@cond_branch
	cmp	r1, #0
	beq	.L22	@cond_branch
	ldr	r0, .L23+8
	cmp	r1, r0
	bgt	.L10	@cond_branch
	ldr	r1, .L23+12
	add	r0, r2, #0
	bl	__mulsf3
	add	r2, r0, #0
	add	r3, r2, #0
	add	r1, r3, #0
	and	r1, r1, r5
	mov	r0, #25
	neg	r0, r0
	str	r0, [r4]
.L10:
	ldr	r0, [r4]
	sub	r0, r0, #126
	asr	r1, r1, #23
	add	r0, r0, r1
	str	r0, [r4]
	ldr	r0, .L23+16
	and	r0, r0, r3
	mov	r1, #252
	lsl	r1, r1, #22
	add	r2, r0, #0
	orr	r2, r2, r1
.L22:
	add	r0, r2, #0
	pop	{r4, r5, pc}
.L24:
	.align	2, 0
.L23:
	.word	2147483647
	.word	2139095039
	.word	8388607
	.word 0x4c000000	@ float 3.35544320000000000000e7
	.word	-2139095041
.Lfe1:
	.size	 frexpf,.Lfe1-frexpf
.text
	.align	2, 0
