@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	ldexpf
	.type	 ldexpf,function
	.thumb_func
ldexpf:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	add	r5, r1, #0
	bl	finitef
	cmp	r0, #0
	beq	.L5	@cond_branch
	ldr	r6, .L8
	add	r0, r4, #0
	add	r1, r6, #0
	bl	__eqsf2
	cmp	r0, #0
	beq	.L5	@cond_branch
	add	r0, r4, #0
	add	r1, r5, #0
	bl	scalbnf
	add	r4, r0, #0
	bl	finitef
	cmp	r0, #0
	beq	.L6	@cond_branch
	add	r0, r4, #0
	add	r1, r6, #0
	bl	__eqsf2
	cmp	r0, #0
	bne	.L5	@cond_branch
.L6:
	bl	__errno
	mov	r1, #34
	str	r1, [r0]
.L5:
	add	r0, r4, #0
	pop	{r4, r5, r6, pc}
.L9:
	.align	2, 0
.L8:
	.word 0x0	@ float 0.00000000000000000000e0
.Lfe1:
	.size	 ldexpf,.Lfe1-ldexpf
.text
	.align	2, 0
