@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
	.type	 two25,object
	.size	 two25,4
two25:
	.word 0x4c000000	@ float 3.35544320000000000000e7
	.align	2, 0
	.type	 twom25,object
	.size	 twom25,4
twom25:
	.word 0x33000000	@ float 2.98023223876953125000e-8
	.align	2, 0
	.type	 huge,object
	.size	 huge,4
huge:
	.word 0x7149f2ca	@ float 1.00000001504746621988e30
	.align	2, 0
	.type	 tiny,object
	.size	 tiny,4
tiny:
	.word 0xda24260	@ float 1.00000000317107685097e-30
.text
	.align	2, 0
	.globl	scalbnf
	.type	 scalbnf,function
	.thumb_func
scalbnf:
	push	{r4, r5, lr}
	add	r3, r0, #0
	add	r4, r1, #0
	add	r1, r3, #0
	mov	r5, #255
	lsl	r5, r5, #23
	add	r0, r1, #0
	and	r0, r0, r5
	asr	r2, r0, #23
	cmp	r2, #0
	bne	.L8	@cond_branch
	ldr	r0, .L37
	and	r1, r1, r0
	cmp	r1, #0
	bne	.L9	@cond_branch
	add	r0, r3, #0
	b	.L32
.L38:
	.align	2, 0
.L37:
	.word	2147483647
.L9:
	ldr	r1, .L39
	add	r0, r3, #0
	bl	__mulsf3
	add	r3, r0, #0
	add	r1, r3, #0
	add	r0, r1, #0
	and	r0, r0, r5
	asr	r0, r0, #23
	add	r2, r0, #0
	sub	r2, r2, #25
	ldr	r0, .L39+4
	cmp	r4, r0
	bge	.L8	@cond_branch
	ldr	r1, .L39+8
	b	.L34
.L40:
	.align	2, 0
.L39:
	.word 0x4c000000	@ float 3.35544320000000000000e7
	.word	-50000
	.word 0xda24260	@ float 1.00000000317107685097e-30
.L8:
	cmp	r2, #255
	bne	.L16	@cond_branch
	add	r0, r3, #0
	add	r1, r3, #0
	bl	__addsf3
	b	.L35
.L16:
	add	r2, r2, r4
	cmp	r2, #254
	ble	.L17	@cond_branch
	ldr	r4, .L41
	add	r0, r4, #0
	add	r1, r3, #0
	bl	copysignf
	add	r1, r4, #0
	b	.L36
.L42:
	.align	2, 0
.L41:
	.word 0x7149f2ca	@ float 1.00000001504746621988e30
.L17:
	cmp	r2, #0
	ble	.L18	@cond_branch
	ldr	r0, .L43
	and	r1, r1, r0
	lsl	r0, r2, #23
	add	r3, r1, #0
	orr	r3, r3, r0
	add	r0, r3, #0
	b	.L32
.L44:
	.align	2, 0
.L43:
	.word	-2139095041
.L18:
	mov	r0, #25
	neg	r0, r0
	cmp	r2, r0
	bgt	.L24	@cond_branch
	ldr	r0, .L45
	cmp	r4, r0
	ble	.L25	@cond_branch
	ldr	r4, .L45+4
	add	r0, r4, #0
	add	r1, r3, #0
	bl	copysignf
	add	r1, r4, #0
	b	.L36
.L46:
	.align	2, 0
.L45:
	.word	50000
	.word 0x7149f2ca	@ float 1.00000001504746621988e30
.L25:
	ldr	r4, .L47
	add	r0, r4, #0
	add	r1, r3, #0
	bl	copysignf
	add	r1, r4, #0
	b	.L36
.L48:
	.align	2, 0
.L47:
	.word 0xda24260	@ float 1.00000000317107685097e-30
.L24:
	add	r2, r2, #25
	ldr	r0, .L49
	and	r1, r1, r0
	lsl	r0, r2, #23
	add	r3, r1, #0
	orr	r3, r3, r0
	ldr	r1, .L49+4
.L34:
	add	r0, r3, #0
.L36:
	bl	__mulsf3
.L35:
.L32:
	pop	{r4, r5, pc}
.L50:
	.align	2, 0
.L49:
	.word	-2139095041
	.word 0x33000000	@ float 2.98023223876953125000e-8
.Lfe1:
	.size	 scalbnf,.Lfe1-scalbnf
.text
	.align	2, 0
