@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	clearerr
	.type	 clearerr,function
	.thumb_func
clearerr:
	mov	r1, #97
	neg	r1, r1
	ldrh	r2, [r0, #12]
	and	r1, r1, r2
	strh	r1, [r0, #12]
	bx	lr
.Lfe1:
	.size	 clearerr,.Lfe1-clearerr
.text
	.align	2, 0
