@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	ferror
	.type	 ferror,function
	.thumb_func
ferror:
	ldrh	r0, [r0, #12]
	lsr	r0, r0, #6
	mov	r1, #1
	and	r0, r0, r1
	bx	lr
.Lfe1:
	.size	 ferror,.Lfe1-ferror
.text
	.align	2, 0
