@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fgets
	.type	 fgets,function
	.thumb_func
fgets:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	mov	r9, r0
	add	r6, r1, #0
	add	r5, r2, #0
	cmp	r6, #1
	bgt	.L3	@cond_branch
.L17:
	mov	r0, #0
	b	.L14
.L15:
	add	r1, r1, #1
	sub	r4, r1, r7
	ldr	r0, [r5, #4]
	sub	r0, r0, r4
	str	r0, [r5, #4]
	str	r1, [r5]
	mov	r0, r8
	add	r1, r7, #0
	add	r2, r4, #0
	bl	memcpy
	mov	r0, r8
	add	r1, r0, r4
	mov	r0, #0
	b	.L16
.L3:
	mov	r8, r9
	sub	r6, r6, #1
	b	.L4
.L8:
	ldr	r4, [r5, #4]
.L7:
	ldr	r7, [r5]
	cmp	r4, r6
	bls	.L10	@cond_branch
	add	r4, r6, #0
.L10:
	add	r0, r7, #0
	mov	r1, #10
	add	r2, r4, #0
	bl	memchr
	add	r1, r0, #0
	cmp	r1, #0
	bne	.L15	@cond_branch
	ldr	r0, [r5, #4]
	sub	r0, r0, r4
	str	r0, [r5, #4]
	ldr	r0, [r5]
	add	r0, r0, r4
	str	r0, [r5]
	mov	r0, r8
	add	r1, r7, #0
	add	r2, r4, #0
	bl	memcpy
	add	r8, r8, r4
	sub	r6, r6, r4
	cmp	r6, #0
	beq	.L5	@cond_branch
.L4:
	ldr	r4, [r5, #4]
	cmp	r4, #0
	bne	.L7	@cond_branch
	add	r0, r5, #0
	bl	__srefill
	cmp	r0, #0
	beq	.L8	@cond_branch
	cmp	r8, r9
	beq	.L17	@cond_branch
.L5:
	mov	r0, #0
	mov	r1, r8
.L16:
	strb	r0, [r1]
	mov	r0, r9
.L14:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 fgets,.Lfe1-fgets
.text
	.align	2, 0
