@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fgetpos
	.type	 fgetpos,function
	.thumb_func
fgetpos:
	push	{r4, lr}
	add	r4, r1, #0
	bl	ftell
	str	r0, [r4]
	mov	r1, #1
	neg	r1, r1
	cmp	r0, r1
	bne	.L3	@cond_branch
	mov	r0, #1
	b	.L4
.L3:
	mov	r0, #0
.L4:
	pop	{r4, pc}
.Lfe1:
	.size	 fgetpos,.Lfe1-fgetpos
.text
	.align	2, 0
