@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fileno
	.type	 fileno,function
	.thumb_func
fileno:
	push	{r4, lr}
	add	r4, r0, #0
	ldr	r0, [r4, #84]
	cmp	r0, #0
	bne	.L6	@cond_branch
	ldr	r0, .L10
	ldr	r0, [r0]
	str	r0, [r4, #84]
.L6:
	ldr	r1, [r4, #84]
	ldr	r0, [r1, #56]
	cmp	r0, #0
	bne	.L4	@cond_branch
	add	r0, r1, #0
	bl	__sinit
.L4:
	mov	r1, #14
	ldrsh	r0, [r4, r1]
	pop	{r4, pc}
.L11:
	.align	2, 0
.L10:
	.word	_impure_ptr
.Lfe1:
	.size	 fileno,.Lfe1-fileno
.text
	.align	2, 0
