@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__sflags
	.type	 __sflags,function
	.thumb_func
__sflags:
	push	{r4, r5, lr}
	add	r3, r0, #0
	add	r4, r2, #0
	ldrb	r0, [r1]
	cmp	r0, #114
	beq	.L4	@cond_branch
	cmp	r0, #114
	bgt	.L9	@cond_branch
	cmp	r0, #97
	beq	.L6	@cond_branch
	b	.L7
.L9:
	cmp	r0, #119
	beq	.L5	@cond_branch
	b	.L7
.L4:
	mov	r2, #4
	mov	r3, #0
	mov	r0, #0
	b	.L3
.L5:
	mov	r2, #8
	mov	r3, #1
	mov	r0, #192
	lsl	r0, r0, #3
	b	.L3
.L6:
	mov	r2, #132
	lsl	r2, r2, #1
	mov	r3, #1
	mov	r0, #130
	lsl	r0, r0, #2
	b	.L3
.L7:
	mov	r0, #22
	str	r0, [r3]
	mov	r0, #0
	b	.L17
.L3:
	ldrb	r5, [r1, #1]
	cmp	r5, #43
	beq	.L11	@cond_branch
	ldrb	r1, [r1, #2]
	cmp	r1, #43
	bne	.L10	@cond_branch
.L11:
	mov	r2, #16
	mov	r3, #2
.L10:
	orr	r3, r3, r0
	str	r3, [r4]
	add	r0, r2, #0
.L17:
	pop	{r4, r5, pc}
.Lfe1:
	.size	 __sflags,.Lfe1-__sflags
.text
	.align	2, 0
