@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_fopen_r
	.type	 _fopen_r,function
	.thumb_func
_fopen_r:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-4
	add	r4, r0, #0
	add	r6, r1, #0
	add	r1, r2, #0
	mov	r2, sp
	bl	__sflags
	add	r5, r0, #0
	cmp	r5, #0
	beq	.L8	@cond_branch
	add	r0, r4, #0
	bl	__sfp
	add	r4, r0, #0
	cmp	r4, #0
	bne	.L4	@cond_branch
.L8:
	mov	r0, #0
	b	.L7
.L4:
	ldr	r0, [r4, #84]
	ldr	r2, [sp]
	mov	r3, #219
	lsl	r3, r3, #1
	add	r1, r6, #0
	bl	_open_r
	cmp	r0, #0
	bge	.L5	@cond_branch
	mov	r0, #0
	strh	r0, [r4, #12]
	b	.L7
.L5:
	strh	r0, [r4, #14]
	strh	r5, [r4, #12]
	str	r4, [r4, #28]
	ldr	r0, .L9
	str	r0, [r4, #32]
	ldr	r0, .L9+4
	str	r0, [r4, #36]
	ldr	r0, .L9+8
	str	r0, [r4, #40]
	ldr	r0, .L9+12
	str	r0, [r4, #44]
	mov	r0, #128
	lsl	r0, r0, #1
	and	r0, r0, r5
	cmp	r0, #0
	beq	.L6	@cond_branch
	add	r0, r4, #0
	mov	r1, #0
	mov	r2, #2
	bl	fseek
.L6:
	add	r0, r4, #0
.L7:
	add	sp, sp, #4
	pop	{r4, r5, r6, pc}
.L10:
	.align	2, 0
.L9:
	.word	__sread
	.word	__swrite
	.word	__sseek
	.word	__sclose
.Lfe1:
	.size	 _fopen_r,.Lfe1-_fopen_r
	.align	2, 0
	.globl	fopen
	.type	 fopen,function
	.thumb_func
fopen:
	push	{lr}
	add	r3, r0, #0
	add	r2, r1, #0
	ldr	r0, .L12
	ldr	r0, [r0]
	add	r1, r3, #0
	bl	_fopen_r
	pop	{pc}
.L13:
	.align	2, 0
.L12:
	.word	_impure_ptr
.Lfe2:
	.size	 fopen,.Lfe2-fopen
.text
	.align	2, 0
