@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fputs
	.type	 fputs,function
	.thumb_func
fputs:
	push	{r4, lr}
	add	sp, sp, #-20
	add	r4, r1, #0
	str	r0, [sp, #12]
	bl	strlen
	str	r0, [sp, #8]
	add	r1, sp, #12
	str	r0, [r1, #4]
	str	r1, [sp]
	mov	r0, #1
	str	r0, [sp, #4]
	add	r0, r4, #0
	mov	r1, sp
	bl	__sfvwrite
	add	sp, sp, #20
	pop	{r4, pc}
.Lfe1:
	.size	 fputs,.Lfe1-fputs
.text
	.align	2, 0
