@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fscanf
	.type	 fscanf,function
	.thumb_func
fscanf:
	push	{r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	add	r2, sp, #8
	bl	__svfscanf
	pop	{r3}
	add	sp, sp, #12
	bx	r3
.Lfe1:
	.size	 fscanf,.Lfe1-fscanf
.text
	.align	2, 0
