@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fsetpos
	.type	 fsetpos,function
	.thumb_func
fsetpos:
	push	{lr}
	ldr	r1, [r1]
	mov	r2, #0
	bl	fseek
	cmp	r0, #0
	bne	.L3	@cond_branch
	mov	r0, #0
	b	.L4
.L3:
	mov	r0, #1
.L4:
	pop	{pc}
.Lfe1:
	.size	 fsetpos,.Lfe1-fsetpos
.text
	.align	2, 0
