@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_getchar_r
	.type	 _getchar_r,function
	.thumb_func
_getchar_r:
	push	{lr}
	ldr	r2, [r0, #4]
	ldr	r0, [r2, #4]
	sub	r0, r0, #1
	str	r0, [r2, #4]
	cmp	r0, #0
	blt	.L3	@cond_branch
	ldr	r1, [r2]
	ldrb	r0, [r1]
	add	r1, r1, #1
	str	r1, [r2]
	b	.L5
.L3:
	add	r0, r2, #0
	bl	__srget
.L5:
	pop	{pc}
.Lfe1:
	.size	 _getchar_r,.Lfe1-_getchar_r
	.align	2, 0
	.globl	getchar
	.type	 getchar,function
	.thumb_func
getchar:
	push	{lr}
	ldr	r0, .L7
	ldr	r0, [r0]
	bl	_getchar_r
	pop	{pc}
.L8:
	.align	2, 0
.L7:
	.word	_impure_ptr
.Lfe2:
	.size	 getchar,.Lfe2-getchar
.text
	.align	2, 0
