@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_gets_r
	.type	 _gets_r,function
	.thumb_func
_gets_r:
	push	{r4, r5, r6, lr}
	add	r6, r0, #0
	add	r5, r1, #0
	add	r4, r5, #0
	b	.L3
.L6:
	strb	r1, [r4]
	add	r4, r4, #1
.L3:
	add	r0, r6, #0
	bl	_getchar_r
	add	r1, r0, #0
	cmp	r1, #10
	beq	.L4	@cond_branch
	mov	r0, #1
	neg	r0, r0
	cmp	r1, r0
	bne	.L6	@cond_branch
	cmp	r4, r5
	bne	.L4	@cond_branch
	mov	r0, #0
	b	.L11
.L4:
	mov	r0, #0
	strb	r0, [r4]
	add	r0, r5, #0
.L11:
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 _gets_r,.Lfe1-_gets_r
	.align	2, 0
	.globl	gets
	.type	 gets,function
	.thumb_func
gets:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L13
	ldr	r0, [r0]
	bl	_gets_r
	pop	{pc}
.L14:
	.align	2, 0
.L13:
	.word	_impure_ptr
.Lfe2:
	.size	 gets,.Lfe2-gets
.text
	.align	2, 0
