@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	iprintf
	.type	 iprintf,function
	.thumb_func
iprintf:
	push	{r0, r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	add	r2, sp, #8
	ldr	r0, .L3
	ldr	r0, [r0]
	ldr	r3, [r0, #8]
	str	r0, [r3, #84]
	ldr	r0, [r0, #8]
	bl	vfiprintf
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 iprintf,.Lfe1-iprintf
	.align	2, 0
	.globl	_iprintf_r
	.type	 _iprintf_r,function
	.thumb_func
_iprintf_r:
	push	{r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	add	r2, sp, #8
	ldr	r0, [r0, #8]
	bl	vfiprintf
	pop	{r3}
	add	sp, sp, #12
	bx	r3
.Lfe2:
	.size	 _iprintf_r,.Lfe2-_iprintf_r
.text
	.align	2, 0
