@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_printf_r
	.type	 _printf_r,function
	.thumb_func
_printf_r:
	push	{r1, r2, r3}
	push	{lr}
	ldr	r2, [sp, #4]
	add	r3, sp, #8
	ldr	r1, [r0, #8]
	bl	_vfprintf_r
	pop	{r3}
	add	sp, sp, #12
	bx	r3
.Lfe1:
	.size	 _printf_r,.Lfe1-_printf_r
	.align	2, 0
	.globl	printf
	.type	 printf,function
	.thumb_func
printf:
	push	{r0, r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	add	r2, sp, #8
	ldr	r0, .L4
	ldr	r0, [r0]
	ldr	r3, [r0, #8]
	str	r0, [r3, #84]
	ldr	r0, [r0, #8]
	bl	vfprintf
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L5:
	.align	2, 0
.L4:
	.word	_impure_ptr
.Lfe2:
	.size	 printf,.Lfe2-printf
.text
	.align	2, 0
