@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_putchar_r
	.type	 _putchar_r,function
	.thumb_func
_putchar_r:
	push	{r4, lr}
	add	r4, r0, #0
	add	r3, r1, #0
	ldr	r1, [r4, #8]
	ldr	r0, [r1, #8]
	sub	r2, r0, #1
	str	r2, [r1, #8]
	cmp	r2, #0
	bge	.L3	@cond_branch
	ldr	r0, [r1, #24]
	cmp	r2, r0
	blt	.L5	@cond_branch
	ldr	r0, [r1]
	strb	r3, [r0]
	ldr	r1, [r4, #8]
	ldr	r0, [r1]
	ldrb	r2, [r0]
	cmp	r2, #10
	bne	.L9	@cond_branch
	mov	r0, #10
	b	.L10
.L5:
	add	r0, r3, #0
.L10:
	bl	__swbuf
	add	r2, r0, #0
	b	.L4
.L3:
	ldr	r0, [r1]
	strb	r3, [r0]
	ldr	r1, [r4, #8]
	ldr	r0, [r1]
.L9:
	ldrb	r2, [r0]
	add	r0, r0, #1
	str	r0, [r1]
.L4:
	add	r0, r2, #0
	pop	{r4, pc}
.Lfe1:
	.size	 _putchar_r,.Lfe1-_putchar_r
	.align	2, 0
	.globl	putchar
	.type	 putchar,function
	.thumb_func
putchar:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L12
	ldr	r0, [r0]
	bl	_putchar_r
	pop	{pc}
.L13:
	.align	2, 0
.L12:
	.word	_impure_ptr
.Lfe2:
	.size	 putchar,.Lfe2-putchar
.text
	.align	2, 0
