@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_remove_r
	.type	 _remove_r,function
	.thumb_func
_remove_r:
	push	{lr}
	bl	_unlink_r
	add	r1, r0, #0
	mov	r0, #1
	neg	r0, r0
	cmp	r1, r0
	beq	.L3	@cond_branch
	mov	r0, #0
	b	.L4
.L3:
	add	r0, r1, #0
.L4:
	pop	{pc}
.Lfe1:
	.size	 _remove_r,.Lfe1-_remove_r
	.align	2, 0
	.globl	remove
	.type	 remove,function
	.thumb_func
remove:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L6
	ldr	r0, [r0]
	bl	_remove_r
	pop	{pc}
.L7:
	.align	2, 0
.L6:
	.word	_impure_ptr
.Lfe2:
	.size	 remove,.Lfe2-remove
.text
	.align	2, 0
