@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_rename_r
	.type	 _rename_r,function
	.thumb_func
_rename_r:
	push	{r4, r5, r6, lr}
	add	r5, r0, #0
	add	r6, r1, #0
	bl	_link_r
	mov	r4, #1
	neg	r4, r4
	cmp	r0, r4
	bne	.L3	@cond_branch
	add	r0, r4, #0
	b	.L5
.L3:
	add	r0, r5, #0
	add	r1, r6, #0
	bl	_unlink_r
	cmp	r0, r4
	beq	.L5	@cond_branch
	mov	r0, #0
.L5:
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 _rename_r,.Lfe1-_rename_r
	.align	2, 0
	.globl	rename
	.type	 rename,function
	.thumb_func
rename:
	push	{lr}
	add	r3, r0, #0
	add	r2, r1, #0
	ldr	r0, .L7
	ldr	r0, [r0]
	add	r1, r3, #0
	bl	_rename_r
	pop	{pc}
.L8:
	.align	2, 0
.L7:
	.word	_impure_ptr
.Lfe2:
	.size	 rename,.Lfe2-rename
.text
	.align	2, 0
