@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	rewind
	.type	 rewind,function
	.thumb_func
rewind:
	push	{r4, lr}
	add	r4, r0, #0
	mov	r1, #0
	mov	r2, #0
	bl	fseek
	mov	r0, #97
	neg	r0, r0
	ldrh	r1, [r4, #12]
	and	r0, r0, r1
	strh	r0, [r4, #12]
	pop	{r4, pc}
.Lfe1:
	.size	 rewind,.Lfe1-rewind
.text
	.align	2, 0
