@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__srget
	.type	 __srget,function
	.thumb_func
__srget:
	push	{r4, lr}
	add	r4, r0, #0
	bl	__srefill
	cmp	r0, #0
	beq	.L3	@cond_branch
	mov	r0, #1
	neg	r0, r0
	b	.L4
.L3:
	ldr	r0, [r4, #4]
	sub	r0, r0, #1
	str	r0, [r4, #4]
	ldr	r1, [r4]
	ldrb	r0, [r1]
	add	r1, r1, #1
	str	r1, [r4]
.L4:
	pop	{r4, pc}
.Lfe1:
	.size	 __srget,.Lfe1-__srget
.text
	.align	2, 0
