@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	scanf
	.type	 scanf,function
	.thumb_func
scanf:
	push	{r0, r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	add	r2, sp, #8
	ldr	r0, .L3
	ldr	r0, [r0]
	ldr	r0, [r0, #4]
	bl	__svfscanf
	pop	{r3}
	add	sp, sp, #16
	bx	r3
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 scanf,.Lfe1-scanf
	.align	2, 0
	.globl	_scanf_r
	.type	 _scanf_r,function
	.thumb_func
_scanf_r:
	push	{r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	add	r2, sp, #8
	ldr	r0, [r0, #4]
	bl	__svfscanf
	pop	{r3}
	add	sp, sp, #12
	bx	r3
.Lfe2:
	.size	 _scanf_r,.Lfe2-_scanf_r
.text
	.align	2, 0
