@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	setbuf
	.type	 setbuf,function
	.thumb_func
setbuf:
	push	{lr}
	mov	r2, #0
	cmp	r1, #0
	bne	.L3	@cond_branch
	mov	r2, #2
.L3:
	mov	r3, #128
	lsl	r3, r3, #3
	bl	setvbuf
	pop	{pc}
.Lfe1:
	.size	 setbuf,.Lfe1-setbuf
.text
	.align	2, 0
