@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_sprintf_r
	.type	 _sprintf_r,function
	.thumb_func
_sprintf_r:
	push	{r2, r3}
	push	{r4, r5, lr}
	add	sp, sp, #-88
	ldr	r4, [sp, #100]
	mov	r3, sp
	mov	r5, #0
	mov	r2, #130
	lsl	r2, r2, #2
	strh	r2, [r3, #12]
	str	r1, [sp]
	str	r1, [sp, #16]
	ldr	r1, .L3
	str	r1, [sp, #8]
	str	r1, [sp, #20]
	str	r0, [sp, #84]
	add	r2, sp, #104
	mov	r0, sp
	add	r1, r4, #0
	bl	vfprintf
	ldr	r1, [sp]
	strb	r5, [r1]
	add	sp, sp, #88
	pop	{r4, r5}
	pop	{r3}
	add	sp, sp, #8
	bx	r3
.L4:
	.align	2, 0
.L3:
	.word	2147483647
.Lfe1:
	.size	 _sprintf_r,.Lfe1-_sprintf_r
	.align	2, 0
	.globl	sprintf
	.type	 sprintf,function
	.thumb_func
sprintf:
	push	{r1, r2, r3}
	push	{r4, lr}
	add	sp, sp, #-88
	ldr	r1, [sp, #96]
	mov	r3, sp
	mov	r4, #0
	mov	r2, #130
	lsl	r2, r2, #2
	strh	r2, [r3, #12]
	str	r0, [sp]
	str	r0, [sp, #16]
	ldr	r0, .L6
	str	r0, [sp, #8]
	str	r0, [sp, #20]
	ldr	r0, .L6+4
	ldr	r0, [r0]
	str	r0, [sp, #84]
	add	r2, sp, #100
	mov	r0, sp
	bl	vfprintf
	ldr	r1, [sp]
	strb	r4, [r1]
	add	sp, sp, #88
	pop	{r4}
	pop	{r3}
	add	sp, sp, #12
	bx	r3
.L7:
	.align	2, 0
.L6:
	.word	2147483647
	.word	_impure_ptr
.Lfe2:
	.size	 sprintf,.Lfe2-sprintf
.text
	.align	2, 0
