@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__sread
	.type	 __sread,function
	.thumb_func
__sread:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r4, r1, #0
	add	r3, r2, #0
	ldr	r0, [r5, #84]
	mov	r2, #14
	ldrsh	r1, [r5, r2]
	add	r2, r4, #0
	bl	_read_r
	add	r1, r0, #0
	cmp	r1, #0
	blt	.L3	@cond_branch
	ldr	r0, [r5, #80]
	add	r0, r0, r1
	str	r0, [r5, #80]
	b	.L4
.L3:
	ldr	r0, .L5
	ldrh	r2, [r5, #12]
	and	r0, r0, r2
	strh	r0, [r5, #12]
.L4:
	add	r0, r1, #0
	pop	{r4, r5, pc}
.L6:
	.align	2, 0
.L5:
	.word	-4097
.Lfe1:
	.size	 __sread,.Lfe1-__sread
	.align	2, 0
	.globl	__swrite
	.type	 __swrite,function
	.thumb_func
__swrite:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	add	r5, r1, #0
	add	r6, r2, #0
	mov	r0, #128
	lsl	r0, r0, #1
	ldrh	r1, [r4, #12]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L8	@cond_branch
	ldr	r0, [r4, #84]
	mov	r2, #14
	ldrsh	r1, [r4, r2]
	mov	r2, #0
	mov	r3, #2
	bl	_lseek_r
.L8:
	ldr	r0, .L9
	ldrh	r1, [r4, #12]
	and	r0, r0, r1
	strh	r0, [r4, #12]
	ldr	r0, [r4, #84]
	mov	r2, #14
	ldrsh	r1, [r4, r2]
	add	r2, r5, #0
	add	r3, r6, #0
	bl	_write_r
	pop	{r4, r5, r6, pc}
.L10:
	.align	2, 0
.L9:
	.word	-4097
.Lfe2:
	.size	 __swrite,.Lfe2-__swrite
	.align	2, 0
	.globl	__sseek
	.type	 __sseek,function
	.thumb_func
__sseek:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r4, r1, #0
	add	r3, r2, #0
	ldr	r0, [r5, #84]
	mov	r2, #14
	ldrsh	r1, [r5, r2]
	add	r2, r4, #0
	bl	_lseek_r
	add	r1, r0, #0
	mov	r0, #1
	neg	r0, r0
	cmp	r1, r0
	bne	.L12	@cond_branch
	ldr	r0, .L14
	ldrh	r2, [r5, #12]
	and	r0, r0, r2
	strh	r0, [r5, #12]
	b	.L13
.L15:
	.align	2, 0
.L14:
	.word	-4097
.L12:
	mov	r2, #128
	lsl	r2, r2, #5
	add	r0, r2, #0
	ldrh	r2, [r5, #12]
	orr	r0, r0, r2
	strh	r0, [r5, #12]
	str	r1, [r5, #80]
.L13:
	add	r0, r1, #0
	pop	{r4, r5, pc}
.Lfe3:
	.size	 __sseek,.Lfe3-__sseek
	.align	2, 0
	.globl	__sclose
	.type	 __sclose,function
	.thumb_func
__sclose:
	push	{lr}
	ldr	r2, [r0, #84]
	mov	r3, #14
	ldrsh	r1, [r0, r3]
	add	r0, r2, #0
	bl	_close_r
	pop	{pc}
.Lfe4:
	.size	 __sclose,.Lfe4-__sclose
.text
	.align	2, 0
