@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	vsprintf
	.type	 vsprintf,function
	.thumb_func
vsprintf:
	push	{r4, r5, lr}
	add	sp, sp, #-88
	mov	r4, sp
	mov	r5, #0
	mov	r3, #130
	lsl	r3, r3, #2
	strh	r3, [r4, #12]
	str	r0, [sp]
	str	r0, [sp, #16]
	ldr	r0, .L3
	str	r0, [sp, #8]
	str	r0, [sp, #20]
	ldr	r0, .L3+4
	ldr	r0, [r0]
	str	r0, [sp, #84]
	mov	r0, sp
	bl	vfprintf
	ldr	r1, [sp]
	strb	r5, [r1]
	add	sp, sp, #88
	pop	{r4, r5, pc}
.L4:
	.align	2, 0
.L3:
	.word	2147483647
	.word	_impure_ptr
.Lfe1:
	.size	 vsprintf,.Lfe1-vsprintf
.text
	.align	2, 0
