@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__swbuf
	.type	 __swbuf,function
	.thumb_func
__swbuf:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r4, r1, #0
	ldr	r0, [r4, #84]
	cmp	r0, #0
	bne	.L6	@cond_branch
	ldr	r0, .L19
	ldr	r0, [r0]
	str	r0, [r4, #84]
.L6:
	ldr	r1, [r4, #84]
	ldr	r0, [r1, #56]
	cmp	r0, #0
	bne	.L4	@cond_branch
	add	r0, r1, #0
	bl	__sinit
.L4:
	ldr	r0, [r4, #24]
	str	r0, [r4, #8]
	mov	r0, #8
	ldrh	r1, [r4, #12]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L11	@cond_branch
	ldr	r0, [r4, #16]
	cmp	r0, #0
	bne	.L10	@cond_branch
.L11:
	add	r0, r4, #0
	bl	__swsetup
	cmp	r0, #0
	bne	.L18	@cond_branch
.L10:
	lsl	r0, r5, #24
	lsr	r5, r0, #24
	ldr	r1, [r4]
	ldr	r0, [r4, #16]
	sub	r2, r1, r0
	ldr	r0, [r4, #20]
	cmp	r2, r0
	blt	.L12	@cond_branch
	add	r0, r4, #0
	bl	fflush
	cmp	r0, #0
	bne	.L18	@cond_branch
	mov	r2, #0
	ldr	r1, [r4]
.L12:
	ldr	r0, [r4, #8]
	sub	r0, r0, #1
	str	r0, [r4, #8]
	strb	r5, [r1]
	add	r0, r1, #1
	str	r0, [r4]
	add	r2, r2, #1
	ldr	r0, [r4, #20]
	cmp	r2, r0
	beq	.L15	@cond_branch
	mov	r0, #1
	ldrh	r1, [r4, #12]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L14	@cond_branch
	cmp	r5, #10
	bne	.L14	@cond_branch
.L15:
	add	r0, r4, #0
	bl	fflush
	cmp	r0, #0
	beq	.L14	@cond_branch
.L18:
	mov	r0, #1
	neg	r0, r0
	b	.L17
.L20:
	.align	2, 0
.L19:
	.word	_impure_ptr
.L14:
	add	r0, r5, #0
.L17:
	pop	{r4, r5, pc}
.Lfe1:
	.size	 __swbuf,.Lfe1-__swbuf
.text
	.align	2, 0
