@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__swsetup
	.type	 __swsetup,function
	.thumb_func
__swsetup:
	push	{r4, r5, lr}
	add	r4, r0, #0
	ldr	r0, [r4, #84]
	cmp	r0, #0
	bne	.L6	@cond_branch
	ldr	r0, .L21
	ldr	r0, [r0]
	str	r0, [r4, #84]
.L6:
	ldr	r1, [r4, #84]
	ldr	r0, [r1, #56]
	cmp	r0, #0
	bne	.L4	@cond_branch
	add	r0, r1, #0
	bl	__sinit
.L4:
	ldrh	r1, [r4, #12]
	mov	r0, #8
	and	r0, r0, r1
	lsl	r0, r0, #16
	asr	r5, r0, #16
	cmp	r5, #0
	bne	.L10	@cond_branch
	mov	r0, #16
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L11	@cond_branch
	mov	r0, #1
	neg	r0, r0
	b	.L20
.L22:
	.align	2, 0
.L21:
	.word	_impure_ptr
.L11:
	mov	r0, #4
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L12	@cond_branch
	ldr	r1, [r4, #48]
	cmp	r1, #0
	beq	.L13	@cond_branch
	add	r0, r4, #0
	add	r0, r0, #64
	cmp	r1, r0
	beq	.L14	@cond_branch
	ldr	r0, [r4, #84]
	bl	_free_r
.L14:
	str	r5, [r4, #48]
.L13:
	mov	r0, #37
	neg	r0, r0
	ldrh	r1, [r4, #12]
	and	r0, r0, r1
	mov	r1, #0
	strh	r0, [r4, #12]
	str	r1, [r4, #4]
	ldr	r0, [r4, #16]
	str	r0, [r4]
.L12:
	mov	r0, #8
	ldrh	r1, [r4, #12]
	orr	r0, r0, r1
	strh	r0, [r4, #12]
.L10:
	ldr	r0, [r4, #16]
	cmp	r0, #0
	bne	.L15	@cond_branch
	add	r0, r4, #0
	bl	__smakebuf
.L15:
	ldrh	r1, [r4, #12]
	mov	r0, #1
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L16	@cond_branch
	mov	r0, #0
	str	r0, [r4, #8]
	ldr	r0, [r4, #20]
	neg	r0, r0
	str	r0, [r4, #24]
	b	.L17
.L16:
	mov	r0, #2
	and	r0, r0, r1
	mov	r1, #0
	cmp	r0, #0
	bne	.L18	@cond_branch
	ldr	r1, [r4, #20]
.L18:
	str	r1, [r4, #8]
.L17:
	mov	r0, #0
.L20:
	pop	{r4, r5, pc}
.Lfe1:
	.size	 __swsetup,.Lfe1-__swsetup
.text
	.align	2, 0
