@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	abort
	.type	 abort,function
	.thumb_func
abort:
	mov	ip, r3
	mov	r3, r8
	push	{r3}
	mov	r3, ip
	mov	r2, #24
	ldr	r3, .L5
	mov r0, r2; mov r1, r3; swi 171; mov r8, r0
	.code	16
	pop	{r3}
	mov	r8, r3
	bx	lr
.L6:
	.align	2, 0
.L5:
	.word	131106
.Lfe1:
	.size	 abort,.Lfe1-abort
	.align	2, 0
	.globl	isatty
	.type	 isatty,function
	.thumb_func
isatty:
	mov	r0, #1
	bx	lr
.Lfe2:
	.size	 isatty,.Lfe2-isatty
	.align	2, 0
	.globl	alarm
	.type	 alarm,function
	.thumb_func
alarm:
	bx	lr
.Lfe3:
	.size	 alarm,.Lfe3-alarm
.text
	.align	2, 0
