@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	close
	.type	 close,function
	.thumb_func
close:
	push	{lr}
	bl	_close
	pop	{pc}
.Lfe1:
	.size	 close,.Lfe1-close
.text
	.align	2, 0
