@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	execve
	.type	 execve,function
	.thumb_func
execve:
	push	{lr}
	bl	_execve
	pop	{pc}
.Lfe1:
	.size	 execve,.Lfe1-execve
.text
	.align	2, 0
