@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fork
	.type	 fork,function
	.thumb_func
fork:
	push	{lr}
	bl	_fork
	pop	{pc}
.Lfe1:
	.size	 fork,.Lfe1-fork
.text
	.align	2, 0
