@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fstat
	.type	 fstat,function
	.thumb_func
fstat:
	push	{lr}
	bl	_fstat
	pop	{pc}
.Lfe1:
	.size	 fstat,.Lfe1-fstat
.text
	.align	2, 0
