@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	fcntl
	.type	 fcntl,function
	.thumb_func
fcntl:
	push	{lr}
	bl	_fcntl
	pop	{pc}
.Lfe1:
	.size	 fcntl,.Lfe1-fcntl
.text
	.align	2, 0
