@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	gettimeofday
	.type	 gettimeofday,function
	.thumb_func
gettimeofday:
	push	{lr}
	bl	_gettimeofday
	pop	{pc}
.Lfe1:
	.size	 gettimeofday,.Lfe1-gettimeofday
.text
	.align	2, 0
