@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	kill
	.type	 kill,function
	.thumb_func
kill:
	push	{lr}
	bl	_kill
	pop	{pc}
.Lfe1:
	.size	 kill,.Lfe1-kill
.text
	.align	2, 0
