@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	lseek
	.type	 lseek,function
	.thumb_func
lseek:
	push	{lr}
	bl	_lseek
	pop	{pc}
.Lfe1:
	.size	 lseek,.Lfe1-lseek
.text
	.align	2, 0
