@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	link
	.type	 link,function
	.thumb_func
link:
	push	{lr}
	bl	_link
	pop	{pc}
.Lfe1:
	.size	 link,.Lfe1-link
.text
	.align	2, 0
