@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	open
	.type	 open,function
	.thumb_func
open:
	push	{r1, r2, r3}
	push	{lr}
	ldr	r1, [sp, #4]
	ldr	r2, [sp, #8]
	bl	_open
	pop	{r3}
	add	sp, sp, #12
	bx	r3
.Lfe1:
	.size	 open,.Lfe1-open
.text
	.align	2, 0
