@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	read
	.type	 read,function
	.thumb_func
read:
	push	{lr}
	bl	_read
	pop	{pc}
.Lfe1:
	.size	 read,.Lfe1-read
.text
	.align	2, 0
