@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	sbrk
	.type	 sbrk,function
	.thumb_func
sbrk:
	push	{lr}
	bl	_sbrk
	pop	{pc}
.Lfe1:
	.size	 sbrk,.Lfe1-sbrk
.text
	.align	2, 0
