@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	stat
	.type	 stat,function
	.thumb_func
stat:
	push	{lr}
	bl	_stat
	pop	{pc}
.Lfe1:
	.size	 stat,.Lfe1-stat
.text
	.align	2, 0
