@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	times
	.type	 times,function
	.thumb_func
times:
	push	{lr}
	bl	_times
	pop	{pc}
.Lfe1:
	.size	 times,.Lfe1-times
.text
	.align	2, 0
