@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	unlink
	.type	 unlink,function
	.thumb_func
unlink:
	push	{lr}
	bl	_unlink
	pop	{pc}
.Lfe1:
	.size	 unlink,.Lfe1-unlink
.text
	.align	2, 0
