@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	wait
	.type	 wait,function
	.thumb_func
wait:
	push	{lr}
	bl	_wait
	pop	{pc}
.Lfe1:
	.size	 wait,.Lfe1-wait
.text
	.align	2, 0
