@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	write
	.type	 write,function
	.thumb_func
write:
	push	{lr}
	bl	_write
	pop	{pc}
.Lfe1:
	.size	 write,.Lfe1-write
.text
	.align	2, 0
