@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
	.type	 powtab.3,object
powtab.3:
	.long 0x3ff00000, 0x0	@ double 1.00000000000000000000e0
	.long 0x40240000, 0x0	@ double 1.00000000000000000000e1
	.long 0x40590000, 0x0	@ double 1.00000000000000000000e2
	.long 0x408f4000, 0x0	@ double 1.00000000000000000000e3
	.long 0x40c38800, 0x0	@ double 1.00000000000000000000e4
.text
	.align	2, 0
	.globl	__exp10
	.type	 __exp10,function
	.thumb_func
__exp10:
	push	{lr}
	add	r1, r0, #0
	cmp	r1, #4
	bhi	.L3	@cond_branch
	ldr	r0, .L10
	lsl	r1, r1, #3
	add	r1, r1, r0
	ldr	r0, [r1]		@ created by thumb_load_double_from_address
	ldr	r1, [r1, #4]		@ created by thumb_load_double_from_address
	b	.L8
.L11:
	.align	2, 0
.L10:
	.word	powtab.3
.L3:
	mov	r0, #1
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L5	@cond_branch
	lsr	r0, r1, #1
	bl	__exp10
	add	r3, r1, #0
	add	r2, r0, #0
	b	.L9
.L5:
	sub	r0, r1, #1
	bl	__exp10
	ldr	r3, .L12+4		@ created by thumb_load_double_from_address
	ldr	r2, .L12		@ created by thumb_load_double_from_address
.L9:
	bl	__muldf3
.L8:
	pop	{pc}
.L13:
	.align	2, 0
.L12:
	.long 0x40240000, 0x0	@ double 1.00000000000000000000e1
.Lfe1:
	.size	 __exp10,.Lfe1-__exp10
.text
	.align	2, 0
