@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__ten_mul
	.type	 __ten_mul,function
	.thumb_func
__ten_mul:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	add	r6, r0, #0
	mov	r8, r1
	ldr	r0, [r6]		@ created by thumb_load_double_from_address
	ldr	r1, [r6, #4]		@ created by thumb_load_double_from_address
	ldr	r3, .L3+4		@ created by thumb_load_double_from_address
	ldr	r2, .L3		@ created by thumb_load_double_from_address
	bl	__muldf3
	add	r5, r1, #0
	add	r4, r0, #0
	str	r4, [r6]
	str	r5, [r6, #4]
	mov	r0, r8
	bl	__floatsidf
	add	r3, r1, #0
	add	r2, r0, #0
	add	r1, r5, #0
	add	r0, r4, #0
	bl	__adddf3
	str	r0, [r6]
	str	r1, [r6, #4]
	mov	r0, #0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, pc}
.L4:
	.align	2, 0
.L3:
	.long 0x40240000, 0x0	@ double 1.00000000000000000000e1
.Lfe1:
	.size	 __ten_mul,.Lfe1-__ten_mul
.text
	.align	2, 0
