@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	_dummy_abort
.data
	.align	2, 0
	.type	 _dummy_abort,object
	.size	 _dummy_abort,4
_dummy_abort:
	.word	1
.text
	.align	2, 0
