@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	abs
	.type	 abs,function
	.thumb_func
abs:
	cmp	r0, #0
	bge	.L3	@cond_branch
	neg	r0, r0
.L3:
	bx	lr
.Lfe1:
	.size	 abs,.Lfe1-abs
.text
	.align	2, 0
