@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2, 0
.LC1:
	.ascii	"assertion \"%s\" failed: file \"%s\", line %d\n\000"
.text
	.align	2, 0
	.globl	__assert
	.type	 __assert,function
	.thumb_func
__assert:
	push	{r4, lr}
	add	sp, sp, #-4
	add	r3, r0, #0
	add	r4, r1, #0
	ldr	r0, .L3
	ldr	r0, [r0]
	ldr	r0, [r0, #12]
	ldr	r1, .L3+4
	str	r4, [sp]
	bl	fiprintf
	bl	abort
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
	.word	.LC1
.Lfe1:
	.size	 __assert,.Lfe1-__assert
.text
	.align	2, 0
