@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	atoff
	.type	 atoff,function
	.thumb_func
atoff:
	push	{lr}
	mov	r1, #0
	bl	strtodf
	pop	{pc}
.Lfe1:
	.size	 atoff,.Lfe1-atoff
.text
	.align	2, 0
