@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	atoi
	.type	 atoi,function
	.thumb_func
atoi:
	push	{lr}
	mov	r1, #0
	mov	r2, #10
	bl	strtol
	pop	{pc}
.Lfe1:
	.size	 atoi,.Lfe1-atoi
.text
	.align	2, 0
