@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	bsearch
	.type	 bsearch,function
	.thumb_func
bsearch:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	sl, r0
	mov	r9, r1
	mov	r8, r3
	mov	r7, #0
	add	r5, r2, #0
	cmp	r5, #0
	beq	.L6	@cond_branch
	cmp	r3, #0
	bne	.L5	@cond_branch
	b	.L6
.L14:
	add	r0, r6, #0
	b	.L13
.L7:
	add	r0, r7, r5
	lsr	r4, r0, #1
	mov	r0, r8
	mul	r0, r0, r4
	mov	r1, r9
	add	r6, r1, r0
	mov	r0, sl
	add	r1, r6, #0
	ldr	r2, [sp, #32]
	bl	_call_via_r2
	cmp	r0, #0
	bge	.L8	@cond_branch
	add	r5, r4, #0
	b	.L5
.L8:
	cmp	r0, #0
	ble	.L14	@cond_branch
	add	r7, r4, #1
.L5:
	cmp	r7, r5
	bcc	.L7	@cond_branch
.L6:
	mov	r0, #0
.L13:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 bsearch,.Lfe1-bsearch
.text
	.align	2, 0
