@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.data
	.align	2, 0
	.type	 initial_env,object
initial_env:
	.word	0
	.size	 initial_env,4
	.globl	environ
	.align	2, 0
	.type	 environ,object
	.size	 environ,4
environ:
	.word	initial_env
.text
	.align	2, 0
