@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__eprintf
	.type	 __eprintf,function
	.thumb_func
__eprintf:
	push	{r4, r5, r6, lr}
	add	sp, sp, #-4
	add	r4, r0, #0
	add	r5, r1, #0
	add	r6, r2, #0
	ldr	r0, .L3
	ldr	r0, [r0]
	ldr	r0, [r0, #12]
	str	r3, [sp]
	add	r1, r4, #0
	add	r2, r5, #0
	add	r3, r6, #0
	bl	fiprintf
	bl	abort
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 __eprintf,.Lfe1-__eprintf
.text
	.align	2, 0
