@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	exit
	.type	 exit,function
	.thumb_func
exit:
	push	{r4, r5, r6, r7, lr}
	add	r7, r0, #0
	ldr	r0, .L14
	ldr	r0, [r0]
	mov	r1, #164
	lsl	r1, r1, #1
	add	r0, r0, r1
	ldr	r6, [r0]
	cmp	r6, #0
	beq	.L4	@cond_branch
.L6:
	ldr	r4, [r6, #4]
	sub	r4, r4, #1
	cmp	r4, #0
	blt	.L5	@cond_branch
	lsl	r0, r4, #2
	add	r0, r0, #8
	add	r5, r0, r6
.L10:
	ldr	r0, [r5]
	bl	_call_via_r0
	sub	r5, r5, #4
	sub	r4, r4, #1
	cmp	r4, #0
	bge	.L10	@cond_branch
.L5:
	ldr	r6, [r6]
	cmp	r6, #0
	bne	.L6	@cond_branch
.L4:
	ldr	r0, .L14
	ldr	r0, [r0]
	ldr	r1, [r0, #60]
	cmp	r1, #0
	beq	.L13	@cond_branch
	bl	_call_via_r1
.L13:
	add	r0, r7, #0
	bl	_exit
.L15:
	.align	2, 0
.L14:
	.word	_impure_ptr
.Lfe1:
	.size	 exit,.Lfe1-exit
.text
	.align	2, 0
