@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	labs
	.type	 labs,function
	.thumb_func
labs:
	cmp	r0, #0
	bge	.L3	@cond_branch
	neg	r0, r0
.L3:
	bx	lr
.Lfe1:
	.size	 labs,.Lfe1-labs
.text
	.align	2, 0
