@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	malloc
	.type	 malloc,function
	.thumb_func
malloc:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L3
	ldr	r0, [r0]
	bl	_malloc_r
	pop	{pc}
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 malloc,.Lfe1-malloc
	.align	2, 0
	.globl	free
	.type	 free,function
	.thumb_func
free:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L6
	ldr	r0, [r0]
	bl	_free_r
	pop	{pc}
.L7:
	.align	2, 0
.L6:
	.word	_impure_ptr
.Lfe2:
	.size	 free,.Lfe2-free
.text
	.align	2, 0
