@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	mblen
	.type	 mblen,function
	.thumb_func
mblen:
	cmp	r0, #0
	beq	.L4	@cond_branch
	ldrb	r0, [r0]
	cmp	r0, #0
	bne	.L3	@cond_branch
.L4:
	mov	r0, #0
	b	.L6
.L3:
	cmp	r1, #0
	beq	.L5	@cond_branch
	mov	r0, #1
	b	.L6
.L5:
	mov	r0, #1
	neg	r0, r0
.L6:
	bx	lr
.Lfe1:
	.size	 mblen,.Lfe1-mblen
.text
	.align	2, 0
