@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_mbstowcs_r
	.type	 _mbstowcs_r,function
	.thumb_func
_mbstowcs_r:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	add	sp, sp, #-4
	mov	r9, r0
	add	r7, r1, #0
	add	r5, r3, #0
	add	r4, r7, #0
	mov	r8, r5
	add	r6, r2, #0
	cmp	r5, #0
	beq	.L4	@cond_branch
.L5:
	ldr	r0, .L11
	ldr	r3, [r0]
	ldr	r0, [sp, #32]
	str	r0, [sp]
	mov	r0, r9
	add	r1, r4, #0
	add	r2, r6, #0
	bl	_mbtowc_r
	add	r1, r0, #0
	mov	r0, #1
	neg	r0, r0
	cmp	r1, r0
	bne	.L6	@cond_branch
	add	r0, r1, #0
	b	.L10
.L12:
	.align	2, 0
.L11:
	.word	__mb_cur_max
.L6:
	cmp	r1, #0
	bne	.L7	@cond_branch
	sub	r0, r4, r7
	asr	r0, r0, #2
	b	.L10
.L7:
	add	r6, r6, r1
	add	r4, r4, #4
	sub	r5, r5, #1
	cmp	r5, #0
	bne	.L5	@cond_branch
.L4:
	mov	r0, r8
.L10:
	add	sp, sp, #4
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 _mbstowcs_r,.Lfe1-_mbstowcs_r
.text
	.align	2, 0
