@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_mbtowc_r
	.type	 _mbtowc_r,function
	.thumb_func
_mbtowc_r:
	add	sp, sp, #-4
	cmp	r1, #0
	bne	.L3	@cond_branch
	mov	r1, sp
.L3:
	cmp	r2, #0
	beq	.L6	@cond_branch
	cmp	r3, #0
	bne	.L5	@cond_branch
	mov	r0, #1
	neg	r0, r0
	b	.L7
.L5:
	ldrb	r0, [r2]
	str	r0, [r1]
	ldrb	r0, [r2]
	cmp	r0, #0
	beq	.L6	@cond_branch
	mov	r0, #1
	b	.L7
.L6:
	mov	r0, #0
.L7:
	add	sp, sp, #4
	bx	lr
.Lfe1:
	.size	 _mbtowc_r,.Lfe1-_mbtowc_r
.text
	.align	2, 0
