@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	mbtowc
	.type	 mbtowc,function
	.thumb_func
mbtowc:
	add	r3, r0, #0
	cmp	r1, #0
	bne	.L3	@cond_branch
	mov	r0, #0
	b	.L7
.L3:
	cmp	r2, #0
	bne	.L4	@cond_branch
	mov	r0, #1
	neg	r0, r0
	b	.L7
.L4:
	cmp	r3, #0
	beq	.L5	@cond_branch
	ldrb	r0, [r1]
	str	r0, [r3]
.L5:
	ldrb	r2, [r1]
	neg	r0, r2
	orr	r0, r0, r2
	lsr	r0, r0, #31
.L7:
	bx	lr
.Lfe1:
	.size	 mbtowc,.Lfe1-mbtowc
.text
	.align	2, 0
