@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__malloc_lock
	.type	 __malloc_lock,function
	.thumb_func
__malloc_lock:
	bx	lr
.Lfe1:
	.size	 __malloc_lock,.Lfe1-__malloc_lock
	.align	2, 0
	.globl	__malloc_unlock
	.type	 __malloc_unlock,function
	.thumb_func
__malloc_unlock:
	bx	lr
.Lfe2:
	.size	 __malloc_unlock,.Lfe2-__malloc_unlock
.text
	.align	2, 0
