@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	mallinfo
	.type	 mallinfo,function
	.thumb_func
mallinfo:
	push	{r4, lr}
	add	r4, r0, #0
	ldr	r0, .L3
	ldr	r1, [r0]
	add	r0, r4, #0
	bl	_mallinfo_r
	add	r0, r4, #0
	pop	{r4, pc}
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 mallinfo,.Lfe1-mallinfo
	.align	2, 0
	.globl	malloc_stats
	.type	 malloc_stats,function
	.thumb_func
malloc_stats:
	push	{lr}
	ldr	r0, .L6
	ldr	r0, [r0]
	bl	_malloc_stats_r
	pop	{pc}
.L7:
	.align	2, 0
.L6:
	.word	_impure_ptr
.Lfe2:
	.size	 malloc_stats,.Lfe2-malloc_stats
	.align	2, 0
	.globl	mallopt
	.type	 mallopt,function
	.thumb_func
mallopt:
	push	{lr}
	add	r3, r0, #0
	add	r2, r1, #0
	ldr	r0, .L9
	ldr	r0, [r0]
	add	r1, r3, #0
	bl	_mallopt_r
	pop	{pc}
.L10:
	.align	2, 0
.L9:
	.word	_impure_ptr
.Lfe3:
	.size	 mallopt,.Lfe3-mallopt
	.section .rodata
	.align	2, 0
.LC3:
	.ascii	"Memory allocation statistics %s\n\000"
.text
	.align	2, 0
	.globl	_mstats_r
	.type	 _mstats_r,function
	.thumb_func
_mstats_r:
	push	{r4, lr}
	add	r4, r0, #0
	add	r2, r1, #0
	ldr	r0, [r4, #12]
	ldr	r1, .L12
	bl	fiprintf
	add	r0, r4, #0
	bl	_malloc_stats_r
	pop	{r4, pc}
.L13:
	.align	2, 0
.L12:
	.word	.LC3
.Lfe4:
	.size	 _mstats_r,.Lfe4-_mstats_r
	.align	2, 0
	.globl	mstats
	.type	 mstats,function
	.thumb_func
mstats:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L15
	ldr	r0, [r0]
	bl	_mstats_r
	pop	{pc}
.L16:
	.align	2, 0
.L15:
	.word	_impure_ptr
.Lfe5:
	.size	 mstats,.Lfe5-mstats
.text
	.align	2, 0
