@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_pvalloc_r
	.type	 _pvalloc_r,function
	.thumb_func
_pvalloc_r:
	push	{lr}
	add	r2, r1, #0
	mov	r1, #128
	lsl	r1, r1, #5
	ldr	r3, .L3
	add	r2, r2, r3
	neg	r3, r1
	and	r2, r2, r3
	bl	_memalign_r
	pop	{pc}
.L4:
	.align	2, 0
.L3:
	.word	4095
.Lfe1:
	.size	 _pvalloc_r,.Lfe1-_pvalloc_r
.text
	.align	2, 0
