@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	rand_r
	.type	 rand_r,function
	.thumb_func
rand_r:
	add	r2, r0, #0
	ldr	r1, [r2]
	ldr	r0, .L3
	mul	r0, r0, r1
	ldr	r1, .L3+4
	add	r0, r0, r1
	str	r0, [r2]
	ldr	r1, .L3+8
	and	r0, r0, r1
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	1103515245
	.word	12345
	.word	2147483647
.Lfe1:
	.size	 rand_r,.Lfe1-rand_r
.text
	.align	2, 0
