@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	realloc
	.type	 realloc,function
	.thumb_func
realloc:
	push	{lr}
	add	r3, r0, #0
	add	r2, r1, #0
	ldr	r0, .L3
	ldr	r0, [r0]
	add	r1, r3, #0
	bl	_realloc_r
	pop	{pc}
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 realloc,.Lfe1-realloc
.text
	.align	2, 0
