@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strdup
	.type	 strdup,function
	.thumb_func
strdup:
	push	{r4, r5, r6, lr}
	add	r5, r0, #0
	bl	strlen
	add	r4, r0, #1
	add	r0, r4, #0
	bl	malloc
	add	r6, r0, #0
	cmp	r0, #0
	beq	.L3	@cond_branch
	add	r1, r5, #0
	add	r2, r4, #0
	bl	memcpy
.L3:
	add	r0, r6, #0
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 strdup,.Lfe1-strdup
.text
	.align	2, 0
