@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_system_r
	.type	 _system_r,function
	.thumb_func
_system_r:
	push	{lr}
	cmp	r1, #0
	beq	.L3	@cond_branch
	bl	__errno
	mov	r1, #88
	str	r1, [r0]
	mov	r0, #1
	neg	r0, r0
	b	.L4
.L3:
	mov	r0, #0
.L4:
	pop	{pc}
.Lfe1:
	.size	 _system_r,.Lfe1-_system_r
	.align	2, 0
	.globl	system
	.type	 system,function
	.thumb_func
system:
	push	{lr}
	add	r1, r0, #0
	ldr	r0, .L6
	ldr	r0, [r0]
	bl	_system_r
	pop	{pc}
.L7:
	.align	2, 0
.L6:
	.word	_impure_ptr
.Lfe2:
	.size	 system,.Lfe2-system
.text
	.align	2, 0
