@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	wcstombs
	.type	 wcstombs,function
	.thumb_func
wcstombs:
	push	{r4, lr}
	add	r3, r0, #0
	add	r4, r1, #0
	mov	r1, #0
	cmp	r2, #0
	beq	.L3	@cond_branch
.L4:
	ldmia	r4!, {r0}
	strb	r0, [r3]
	lsl	r0, r0, #24
	add	r3, r3, #1
	cmp	r0, #0
	beq	.L3	@cond_branch
	add	r1, r1, #1
	sub	r2, r2, #1
	cmp	r2, #0
	bne	.L4	@cond_branch
.L3:
	add	r0, r1, #0
	pop	{r4, pc}
.Lfe1:
	.size	 wcstombs,.Lfe1-wcstombs
.text
	.align	2, 0
