@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	wctomb
	.type	 wctomb,function
	.thumb_func
wctomb:
	cmp	r0, #0
	beq	.L3	@cond_branch
	strb	r1, [r0]
	mov	r0, #1
	b	.L4
.L3:
	mov	r0, #0
.L4:
	bx	lr
.Lfe1:
	.size	 wctomb,.Lfe1-wctomb
.text
	.align	2, 0
