thumb.o: thumb.c config.h gansidecl.h telf.h thumb.h rtl.h machmode.h \
 machmode.def rtl.def genrtl.h hard-reg-set.h regs.h varray.h system.h \
 output.h insn-flags.h insn-attr.h insn-config.h flags.h tree.h tree.def \
 tree-check.h real.h expr.h insn-codes.h toplev.h recog.h
config.h:
gansidecl.h:
telf.h:
thumb.h:
rtl.h:
machmode.h:
machmode.def:
rtl.def:
genrtl.h:
hard-reg-set.h:
regs.h:
varray.h:
system.h:
output.h:
insn-flags.h:
insn-attr.h:
insn-config.h:
flags.h:
tree.h:
tree.def:
tree-check.h:
real.h:
expr.h:
insn-codes.h:
toplev.h:
recog.h:
