@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.data
	.align	2, 0
	.type	 impure_data,object
	.size	 impure_data,748
impure_data:
	.word	0
	.word	impure_data+484
	.word	impure_data+572
	.word	impure_data+660
	.word	0
	.ascii	"\000"
	.space	24
	.space	3
	.word	0
	.word	.LC0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	1
	.word	0
	.ascii	"\000"
	.space	25
	.space	2
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.space	4
	.word	0
	.space	164
	.space	420
	.section .rodata
	.align	2, 0
.LC0:
	.ascii	"C\000"
	.globl	_impure_ptr
.data
	.align	2, 0
	.type	 _impure_ptr,object
	.size	 _impure_ptr,4
_impure_ptr:
	.word	impure_data
.text
	.align	2, 0
