@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_times_r
	.type	 _times_r,function
	.thumb_func
_times_r:
	push	{lr}
	add	r0, r1, #0
	bl	_times
	pop	{pc}
.Lfe1:
	.size	 _times_r,.Lfe1-_times_r
	.align	2, 0
	.globl	_gettimeofday_r
	.type	 _gettimeofday_r,function
	.thumb_func
_gettimeofday_r:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r0, r1, #0
	add	r1, r2, #0
	ldr	r4, .L5
	mov	r2, #0
	str	r2, [r4]
	bl	_gettimeofday
	add	r1, r0, #0
	mov	r0, #1
	neg	r0, r0
	cmp	r1, r0
	bne	.L4	@cond_branch
	ldr	r0, [r4]
	cmp	r0, #0
	beq	.L4	@cond_branch
	str	r0, [r5]
.L4:
	add	r0, r1, #0
	pop	{r4, r5, pc}
.L6:
	.align	2, 0
.L5:
	.word	errno
.Lfe2:
	.size	 _gettimeofday_r,.Lfe2-_gettimeofday_r
.text
	.align	2, 0
