@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	isascii
	.type	 isascii,function
	.thumb_func
isascii:
	mov	r1, #0
	cmp	r0, #127
	bhi	.L3	@cond_branch
	mov	r1, #1
.L3:
	add	r0, r1, #0
	bx	lr
.Lfe1:
	.size	 isascii,.Lfe1-isascii
.text
	.align	2, 0
