/* Generated automatically by the program `gencodes'
from the machine description file `md'.  */

#ifndef MAX_INSN_CODE

enum insn_code {
  CODE_FOR_movsi = 0,
  CODE_FOR_movhi = 4,
  CODE_FOR_movqi = 6,
  CODE_FOR_movdi = 8,
  CODE_FOR_movdf = 10,
  CODE_FOR_movsf = 12,
  CODE_FOR_zero_extendhisi2 = 14,
  CODE_FOR_zero_extendqisi2 = 16,
  CODE_FOR_extendhisi2 = 18,
  CODE_FOR_extendqisi2 = 20,
  CODE_FOR_extzv = 22,
  CODE_FOR_movstrqi = 23,
  CODE_FOR_movmem12b = 24,
  CODE_FOR_movmem8b = 25,
  CODE_FOR_adddi3 = 26,
  CODE_FOR_addsi3 = 27,
  CODE_FOR_subdi3 = 29,
  CODE_FOR_subsi3 = 30,
  CODE_FOR_mulsi3 = 31,
  CODE_FOR_negsi2 = 32,
  CODE_FOR_andsi3 = 33,
  CODE_FOR_bicsi3 = 35,
  CODE_FOR_iorsi3 = 36,
  CODE_FOR_xorsi3 = 37,
  CODE_FOR_one_cmplsi2 = 38,
  CODE_FOR_ashlsi3 = 39,
  CODE_FOR_ashrsi3 = 40,
  CODE_FOR_lshrsi3 = 41,
  CODE_FOR_rotrsi3 = 42,
  CODE_FOR_cmpsi = 43,
  CODE_FOR_tstsi = 45,
  CODE_FOR_cmnsi = 46,
  CODE_FOR_jump = 47,
  CODE_FOR_beq = 48,
  CODE_FOR_bne = 49,
  CODE_FOR_bge = 50,
  CODE_FOR_ble = 51,
  CODE_FOR_bgt = 52,
  CODE_FOR_blt = 53,
  CODE_FOR_bgeu = 54,
  CODE_FOR_bleu = 55,
  CODE_FOR_bgtu = 56,
  CODE_FOR_bltu = 57,
  CODE_FOR_indirect_jump = 60,
  CODE_FOR_tablejump = 61,
  CODE_FOR_call = 62,
  CODE_FOR_call_value = 64,
  CODE_FOR_nop = 68,
  CODE_FOR_blockage = 69,
  CODE_FOR_prologue = 70,
  CODE_FOR_epilogue = 71,
  CODE_FOR_consttable_4 = 73,
  CODE_FOR_consttable_8 = 74,
  CODE_FOR_consttable_end = 75,
  CODE_FOR_align_4 = 76,
  CODE_FOR_nothing };

#define MAX_INSN_CODE ((int) CODE_FOR_nothing)
#endif /* MAX_INSN_CODE */
