@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	__errno
	.type	 __errno,function
	.thumb_func
__errno:
	ldr	r0, .L3
	ldr	r0, [r0]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 __errno,.Lfe1-__errno
.text
	.align	2, 0
