@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	bcmp
	.type	 bcmp,function
	.thumb_func
bcmp:
	push	{lr}
	bl	memcmp
	pop	{pc}
.Lfe1:
	.size	 bcmp,.Lfe1-bcmp
.text
	.align	2, 0
