@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	bcopy
	.type	 bcopy,function
	.thumb_func
bcopy:
	push	{lr}
	add	r3, r0, #0
	add	r0, r1, #0
	add	r1, r3, #0
	bl	memmove
	pop	{pc}
.Lfe1:
	.size	 bcopy,.Lfe1-bcopy
.text
	.align	2, 0
