@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	bzero
	.type	 bzero,function
	.thumb_func
bzero:
	add	r2, r0, #0
	add	r0, r1, #0
	sub	r1, r1, #1
	cmp	r0, #0
	beq	.L4	@cond_branch
	mov	r3, #0
.L5:
	strb	r3, [r2]
	add	r2, r2, #1
	add	r0, r1, #0
	sub	r1, r1, #1
	cmp	r0, #0
	bne	.L5	@cond_branch
.L4:
	bx	lr
.Lfe1:
	.size	 bzero,.Lfe1-bzero
.text
	.align	2, 0
