@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	index
	.type	 index,function
	.thumb_func
index:
	push	{lr}
	bl	strchr
	pop	{pc}
.Lfe1:
	.size	 index,.Lfe1-index
.text
	.align	2, 0
