@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	memchr
	.type	 memchr,function
	.thumb_func
memchr:
	push	{r4, r5, r6, r7, lr}
	add	r5, r1, #0
	add	r1, r0, #0
	mov	r0, #255
	and	r5, r5, r0
	cmp	r2, #3
	bls	.L28	@cond_branch
	mov	r0, #3
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L28	@cond_branch
	add	r4, r1, #0
	mov	r6, #0
	mov	r1, #0
.L7:
	lsl	r0, r6, #8
	add	r6, r0, r5
	add	r1, r1, #1
	cmp	r1, #3
	bls	.L7	@cond_branch
	cmp	r2, #3
	bls	.L26	@cond_branch
	ldr	r0, .L29
	mov	ip, r0
	ldr	r7, .L29+4
.L11:
	ldr	r1, [r4]
	eor	r1, r1, r6
	mov	r3, ip
	add	r0, r1, r3
	bic	r0, r0, r1
	and	r0, r0, r7
	cmp	r0, #0
	beq	.L12	@cond_branch
	add	r1, r4, #0
	mov	r3, #0
.L16:
	ldrb	r0, [r1]
	cmp	r0, r5
	beq	.L27	@cond_branch
	add	r1, r1, #1
	add	r3, r3, #1
	cmp	r3, #3
	bls	.L16	@cond_branch
.L12:
	sub	r2, r2, #4
	add	r4, r4, #4
	cmp	r2, #3
	bhi	.L11	@cond_branch
.L26:
	add	r1, r4, #0
	b	.L28
.L30:
	.align	2, 0
.L29:
	.word	-16843009
	.word	-2139062144
.L22:
	ldrb	r0, [r1]
	cmp	r0, r5
	bne	.L23	@cond_branch
.L27:
	add	r0, r1, #0
	b	.L25
.L23:
	add	r1, r1, #1
.L28:
	add	r0, r2, #0
	sub	r2, r2, #1
	cmp	r0, #0
	bne	.L22	@cond_branch
	mov	r0, #0
.L25:
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 memchr,.Lfe1-memchr
.text
	.align	2, 0
