@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	memcpy
	.type	 memcpy,function
	.thumb_func
memcpy:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r4, r5, #0
	add	r3, r1, #0
	cmp	r2, #15
	bls	.L3	@cond_branch
	add	r0, r3, #0
	orr	r0, r0, r5
	mov	r1, #3
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L3	@cond_branch
	add	r1, r5, #0
.L6:
	ldmia	r3!, {r0}
	stmia	r1!, {r0}
	ldmia	r3!, {r0}
	stmia	r1!, {r0}
	ldmia	r3!, {r0}
	stmia	r1!, {r0}
	ldmia	r3!, {r0}
	stmia	r1!, {r0}
	sub	r2, r2, #16
	cmp	r2, #15
	bhi	.L6	@cond_branch
	cmp	r2, #3
	bls	.L16	@cond_branch
.L10:
	ldmia	r3!, {r0}
	stmia	r1!, {r0}
	sub	r2, r2, #4
	cmp	r2, #3
	bhi	.L10	@cond_branch
.L16:
	add	r4, r1, #0
.L3:
	sub	r2, r2, #1
	mov	r0, #1
	neg	r0, r0
	cmp	r2, r0
	beq	.L13	@cond_branch
	add	r1, r0, #0
.L14:
	ldrb	r0, [r3]
	strb	r0, [r4]
	add	r3, r3, #1
	add	r4, r4, #1
	sub	r2, r2, #1
	cmp	r2, r1
	bne	.L14	@cond_branch
.L13:
	add	r0, r5, #0
	pop	{r4, r5, pc}
.Lfe1:
	.size	 memcpy,.Lfe1-memcpy
.text
	.align	2, 0
