@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	memmove
	.type	 memmove,function
	.thumb_func
memmove:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r4, r5, #0
	add	r3, r1, #0
	cmp	r3, r5
	bcs	.L3	@cond_branch
	add	r0, r3, r2
	cmp	r5, r0
	bcs	.L3	@cond_branch
	add	r3, r0, #0
	add	r4, r5, r2
	sub	r2, r2, #1
	mov	r0, #1
	neg	r0, r0
	cmp	r2, r0
	beq	.L8	@cond_branch
	add	r1, r0, #0
.L6:
	sub	r4, r4, #1
	sub	r3, r3, #1
	ldrb	r0, [r3]
	strb	r0, [r4]
	sub	r2, r2, #1
	cmp	r2, r1
	bne	.L6	@cond_branch
	b	.L8
.L3:
	cmp	r2, #15
	bls	.L9	@cond_branch
	add	r0, r3, #0
	orr	r0, r0, r4
	mov	r1, #3
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L9	@cond_branch
	add	r1, r3, #0
.L12:
	ldmia	r1!, {r0}
	stmia	r4!, {r0}
	ldmia	r1!, {r0}
	stmia	r4!, {r0}
	ldmia	r1!, {r0}
	stmia	r4!, {r0}
	ldmia	r1!, {r0}
	stmia	r4!, {r0}
	sub	r2, r2, #16
	cmp	r2, #15
	bhi	.L12	@cond_branch
	cmp	r2, #3
	bls	.L22	@cond_branch
.L16:
	ldmia	r1!, {r0}
	stmia	r4!, {r0}
	sub	r2, r2, #4
	cmp	r2, #3
	bhi	.L16	@cond_branch
.L22:
	add	r3, r1, #0
.L9:
	sub	r2, r2, #1
	mov	r0, #1
	neg	r0, r0
	cmp	r2, r0
	beq	.L8	@cond_branch
	add	r1, r0, #0
.L20:
	ldrb	r0, [r3]
	strb	r0, [r4]
	add	r3, r3, #1
	add	r4, r4, #1
	sub	r2, r2, #1
	cmp	r2, r1
	bne	.L20	@cond_branch
.L8:
	add	r0, r5, #0
	pop	{r4, r5, pc}
.Lfe1:
	.size	 memmove,.Lfe1-memmove
.text
	.align	2, 0
