@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	memset
	.type	 memset,function
	.thumb_func
memset:
	push	{r4, r5, lr}
	add	r5, r0, #0
	add	r4, r1, #0
	add	r3, r5, #0
	cmp	r2, #3
	bls	.L26	@cond_branch
	mov	r0, #3
	and	r0, r0, r5
	cmp	r0, #0
	bne	.L26	@cond_branch
	add	r1, r5, #0
	mov	r0, #255
	and	r4, r4, r0
	lsl	r3, r4, #8
	orr	r3, r3, r4
	lsl	r0, r3, #16
	orr	r3, r3, r0
	cmp	r2, #15
	bls	.L25	@cond_branch
.L13:
	stmia	r1!, {r3}
	stmia	r1!, {r3}
	stmia	r1!, {r3}
	stmia	r1!, {r3}
	sub	r2, r2, #16
	cmp	r2, #15
	bhi	.L13	@cond_branch
	b	.L25
.L17:
	stmia	r1!, {r3}
	sub	r2, r2, #4
.L25:
	cmp	r2, #3
	bhi	.L17	@cond_branch
	add	r3, r1, #0
	b	.L26
.L21:
	strb	r4, [r3]
	add	r3, r3, #1
.L26:
	add	r0, r2, #0
	sub	r2, r2, #1
	cmp	r0, #0
	bne	.L21	@cond_branch
	add	r0, r5, #0
	pop	{r4, r5, pc}
.Lfe1:
	.size	 memset,.Lfe1-memset
.text
	.align	2, 0
