@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	rindex
	.type	 rindex,function
	.thumb_func
rindex:
	push	{lr}
	bl	strrchr
	pop	{pc}
.Lfe1:
	.size	 rindex,.Lfe1-rindex
.text
	.align	2, 0
