@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strcat
	.type	 strcat,function
	.thumb_func
strcat:
	push	{r4, r5, r6, lr}
	add	r2, r0, #0
	add	r6, r1, #0
	add	r4, r2, #0
	mov	r0, #3
	and	r0, r0, r4
	cmp	r0, #0
	bne	.L13	@cond_branch
	ldr	r1, [r4]
	ldr	r5, .L14
	add	r0, r1, r5
	bic	r0, r0, r1
	ldr	r3, .L14+4
	b	.L12
.L15:
	.align	2, 0
.L14:
	.word	-16843009
	.word	-2139062144
.L6:
	add	r2, r2, #4
	ldr	r1, [r2]
	add	r0, r1, r5
	bic	r0, r0, r1
.L12:
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L6	@cond_branch
	b	.L13
.L10:
	add	r2, r2, #1
.L13:
	ldrb	r0, [r2]
	cmp	r0, #0
	bne	.L10	@cond_branch
	add	r0, r2, #0
	add	r1, r6, #0
	bl	strcpy
	add	r0, r4, #0
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 strcat,.Lfe1-strcat
.text
	.align	2, 0
