@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strcpy
	.type	 strcpy,function
	.thumb_func
strcpy:
	push	{r4, r5, r6, lr}
	add	r6, r0, #0
	add	r3, r6, #0
	add	r2, r1, #0
	add	r0, r2, #0
	orr	r0, r0, r6
	mov	r1, #3
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L3	@cond_branch
	ldr	r1, [r2]
	ldr	r5, .L13
	add	r0, r1, r5
	bic	r0, r0, r1
	ldr	r4, .L13+4
	b	.L12
.L14:
	.align	2, 0
.L13:
	.word	-16843009
	.word	-2139062144
.L6:
	ldmia	r2!, {r0}
	stmia	r3!, {r0}
	ldr	r1, [r2]
	add	r0, r1, r5
	bic	r0, r0, r1
.L12:
	and	r0, r0, r4
	cmp	r0, #0
	beq	.L6	@cond_branch
.L3:
.L8:
	ldrb	r0, [r2]
	strb	r0, [r3]
	lsl	r0, r0, #24
	add	r2, r2, #1
	add	r3, r3, #1
	cmp	r0, #0
	bne	.L8	@cond_branch
	add	r0, r6, #0
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 strcpy,.Lfe1-strcpy
.text
	.align	2, 0
