@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strlen
	.type	 strlen,function
	.thumb_func
strlen:
	push	{r4, r5, lr}
	add	r1, r0, #0
	add	r5, r1, #0
	mov	r0, #3
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L13	@cond_branch
	add	r2, r1, #0
	ldr	r1, [r2]
	ldr	r4, .L14
	add	r0, r1, r4
	bic	r0, r0, r1
	ldr	r3, .L14+4
	b	.L12
.L15:
	.align	2, 0
.L14:
	.word	-16843009
	.word	-2139062144
.L6:
	add	r2, r2, #4
	ldr	r1, [r2]
	add	r0, r1, r4
	bic	r0, r0, r1
.L12:
	and	r0, r0, r3
	cmp	r0, #0
	beq	.L6	@cond_branch
	add	r1, r2, #0
	b	.L13
.L10:
	add	r1, r1, #1
.L13:
	ldrb	r0, [r1]
	cmp	r0, #0
	bne	.L10	@cond_branch
	sub	r0, r1, r5
	pop	{r4, r5, pc}
.Lfe1:
	.size	 strlen,.Lfe1-strlen
.text
	.align	2, 0
