@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strncmp
	.type	 strncmp,function
	.thumb_func
strncmp:
	push	{r4, r5, r6, lr}
	add	r6, r0, #0
	add	r4, r1, #0
	cmp	r2, #0
	beq	.L17	@cond_branch
	add	r0, r6, #0
	orr	r0, r0, r4
	mov	r1, #3
	and	r0, r0, r1
	cmp	r0, #0
	bne	.L4	@cond_branch
	add	r3, r6, #0
	add	r5, r4, #0
	cmp	r2, #3
	bls	.L6	@cond_branch
	ldr	r1, [r6]
	ldr	r0, [r4]
	cmp	r1, r0
	bne	.L6	@cond_branch
	ldr	r6, .L21
	ldr	r4, .L21+4
.L7:
	sub	r2, r2, #4
	cmp	r2, #0
	beq	.L17	@cond_branch
	ldr	r1, [r3]
	add	r0, r1, r6
	bic	r0, r0, r1
	and	r0, r0, r4
	cmp	r0, #0
	bne	.L17	@cond_branch
	add	r3, r3, #4
	add	r5, r5, #4
	cmp	r2, #3
	bls	.L6	@cond_branch
	ldr	r1, [r3]
	ldr	r0, [r5]
	cmp	r1, r0
	beq	.L7	@cond_branch
.L6:
	add	r6, r3, #0
	add	r4, r5, #0
.L4:
	add	r0, r2, #0
	sub	r2, r2, #1
	cmp	r0, #0
	beq	.L13	@cond_branch
	b	.L20
.L22:
	.align	2, 0
.L21:
	.word	-16843009
	.word	-2139062144
.L14:
	cmp	r2, #0
	beq	.L17	@cond_branch
	cmp	r0, #0
	bne	.L16	@cond_branch
.L17:
	mov	r0, #0
	b	.L19
.L16:
	add	r6, r6, #1
	add	r4, r4, #1
	sub	r2, r2, #1
.L20:
	ldrb	r0, [r6]
	ldrb	r1, [r4]
	cmp	r0, r1
	beq	.L14	@cond_branch
.L13:
	ldrb	r6, [r6]
	ldrb	r4, [r4]
	sub	r0, r6, r4
.L19:
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 strncmp,.Lfe1-strncmp
.text
	.align	2, 0
