@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strpbrk
	.type	 strpbrk,function
	.thumb_func
strpbrk:
	push	{r4, lr}
	add	r4, r0, #0
	ldrb	r0, [r4]
	cmp	r0, #0
	bne	.L6	@cond_branch
	mov	r0, #0
	b	.L16
.L6:
	add	r2, r1, #0
	ldrb	r3, [r2]
	cmp	r3, #0
	beq	.L18	@cond_branch
	ldrb	r0, [r4]
	cmp	r0, r3
	beq	.L8	@cond_branch
	add	r3, r0, #0
.L9:
	add	r2, r2, #1
	ldrb	r0, [r2]
	cmp	r0, #0
	beq	.L18	@cond_branch
	cmp	r3, r0
	bne	.L9	@cond_branch
.L8:
	ldrb	r0, [r2]
	cmp	r0, #0
	bne	.L15	@cond_branch
.L18:
	add	r4, r4, #1
	ldrb	r0, [r4]
	cmp	r0, #0
	bne	.L6	@cond_branch
	ldrb	r0, [r2]
	cmp	r0, #0
	bne	.L15	@cond_branch
	mov	r4, #0
.L15:
	add	r0, r4, #0
.L16:
	pop	{r4, pc}
.Lfe1:
	.size	 strpbrk,.Lfe1-strpbrk
.text
	.align	2, 0
