@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strrchr
	.type	 strrchr,function
	.thumb_func
strrchr:
	mov	r3, #0
	lsl	r1, r1, #24
	lsr	r1, r1, #24
	b	.L9
.L5:
	cmp	r2, r1
	bne	.L6	@cond_branch
	add	r3, r0, #0
.L6:
	add	r0, r0, #1
.L9:
	ldrb	r2, [r0]
	cmp	r2, #0
	bne	.L5	@cond_branch
	ldrb	r2, [r0]
	cmp	r2, r1
	bne	.L8	@cond_branch
	add	r3, r0, #0
.L8:
	add	r0, r3, #0
	bx	lr
.Lfe1:
	.size	 strrchr,.Lfe1-strrchr
.text
	.align	2, 0
