@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strstr
	.type	 strstr,function
	.thumb_func
strstr:
	push	{r4, lr}
	add	r3, r0, #0
	add	r4, r1, #0
	ldrb	r0, [r3]
	cmp	r0, #0
	bne	.L7	@cond_branch
	ldrb	r0, [r4]
	cmp	r0, #0
	bne	.L19	@cond_branch
.L17:
	add	r0, r3, #0
	b	.L15
.L7:
	mov	r1, #0
	ldrb	r0, [r4]
	cmp	r0, #0
	beq	.L17	@cond_branch
	ldrb	r2, [r3]
	cmp	r0, r2
	bne	.L18	@cond_branch
.L12:
	add	r1, r1, #1
	add	r0, r4, r1
	ldrb	r2, [r0]
	cmp	r2, #0
	beq	.L17	@cond_branch
	add	r0, r3, r1
	ldrb	r0, [r0]
	cmp	r2, r0
	beq	.L12	@cond_branch
.L18:
	add	r3, r3, #1
	ldrb	r0, [r3]
	cmp	r0, #0
	bne	.L7	@cond_branch
.L19:
	mov	r0, #0
.L15:
	pop	{r4, pc}
.Lfe1:
	.size	 strstr,.Lfe1-strstr
.text
	.align	2, 0
