@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strtok_r
	.type	 strtok_r,function
	.thumb_func
strtok_r:
	push	{r4, r5, r6, r7, lr}
	add	r4, r0, #0
	add	r7, r1, #0
	add	r6, r2, #0
	cmp	r4, #0
	bne	.L4	@cond_branch
	ldr	r4, [r6]
	cmp	r4, #0
	bne	.L4	@cond_branch
	mov	r0, #0
	b	.L23
.L4:
	ldrb	r1, [r4]
	add	r4, r4, #1
	add	r3, r7, #0
	b	.L24
.L8:
	cmp	r1, r0
	beq	.L4	@cond_branch
.L24:
	ldrb	r0, [r3]
	add	r3, r3, #1
	cmp	r0, #0
	bne	.L8	@cond_branch
	cmp	r1, #0
	bne	.L11	@cond_branch
	str	r1, [r6]
	mov	r0, #0
	b	.L23
.L11:
	sub	r5, r4, #1
.L12:
	ldrb	r1, [r4]
	add	r4, r4, #1
	add	r3, r7, #0
	mov	r2, #0
.L15:
	ldrb	r0, [r3]
	add	r3, r3, #1
	cmp	r0, r1
	bne	.L17	@cond_branch
	cmp	r0, #0
	bne	.L19	@cond_branch
	mov	r4, #0
	b	.L20
.L19:
	sub	r0, r4, #1
	strb	r2, [r0]
.L20:
	str	r4, [r6]
	add	r0, r5, #0
	b	.L23
.L17:
	cmp	r0, #0
	bne	.L15	@cond_branch
	b	.L12
.L23:
	pop	{r4, r5, r6, r7, pc}
.Lfe1:
	.size	 strtok_r,.Lfe1-strtok_r
.text
	.align	2, 0
