@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strtok
	.type	 strtok,function
	.thumb_func
strtok:
	push	{lr}
	ldr	r2, .L3
	ldr	r2, [r2]
	add	r2, r2, #92
	bl	strtok_r
	pop	{pc}
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 strtok,.Lfe1-strtok
.text
	.align	2, 0
