@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strupr
	.type	 strupr,function
	.thumb_func
strupr:
	push	{r4, r5, r6, lr}
	add	r4, r0, #0
	add	r3, r4, #0
	ldrb	r0, [r4]
	cmp	r0, #0
	beq	.L4	@cond_branch
	ldr	r5, .L9
	mov	r6, #2
.L5:
	ldrb	r2, [r3]
	add	r1, r2, r5
	add	r0, r6, #0
	ldrb	r1, [r1]
	and	r0, r0, r1
	cmp	r0, #0
	beq	.L6	@cond_branch
	add	r0, r2, #0
	sub	r0, r0, #32
	strb	r0, [r3]
.L6:
	add	r3, r3, #1
	ldrb	r0, [r3]
	cmp	r0, #0
	bne	.L5	@cond_branch
.L4:
	add	r0, r4, #0
	pop	{r4, r5, r6, pc}
.L10:
	.align	2, 0
.L9:
	.word	_ctype_+1
.Lfe1:
	.size	 strupr,.Lfe1-strupr
.text
	.align	2, 0
