@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	strxfrm
	.type	 strxfrm,function
	.thumb_func
strxfrm:
	push	{r4, lr}
	add	r3, r0, #0
	mov	r4, #0
	b	.L15
.L5:
	ldrb	r0, [r1]
	strb	r0, [r3]
	lsl	r0, r0, #24
	add	r1, r1, #1
	add	r3, r3, #1
	cmp	r0, #0
	beq	.L14	@cond_branch
	add	r4, r4, #1
.L15:
	add	r0, r2, #0
	sub	r2, r2, #1
	cmp	r0, #0
	bne	.L5	@cond_branch
	b	.L16
.L11:
	add	r1, r1, #1
	add	r4, r4, #1
.L16:
	ldrb	r0, [r1]
	cmp	r0, #0
	bne	.L11	@cond_branch
.L14:
	add	r0, r4, #0
	pop	{r4, pc}
.Lfe1:
	.size	 strxfrm,.Lfe1-strxfrm
.text
	.align	2, 0
