@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	_user_strerror
	.type	 _user_strerror,function
	.thumb_func
_user_strerror:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 _user_strerror,.Lfe1-_user_strerror
.text
	.align	2, 0
