@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	asctime
	.type	 asctime,function
	.thumb_func
asctime:
	push	{lr}
	ldr	r1, .L3
	ldr	r1, [r1]
	add	r1, r1, #96
	bl	asctime_r
	pop	{pc}
.L4:
	.align	2, 0
.L3:
	.word	_impure_ptr
.Lfe1:
	.size	 asctime,.Lfe1-asctime
.text
	.align	2, 0
