@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.type	 day_name.3,object
	.size	 day_name.3,21
day_name.3:
	.ascii	"Sun"
	.ascii	"Mon"
	.ascii	"Tue"
	.ascii	"Wed"
	.ascii	"Thu"
	.ascii	"Fri"
	.ascii	"Sat"
	.type	 mon_name.4,object
	.size	 mon_name.4,36
mon_name.4:
	.ascii	"Jan"
	.ascii	"Feb"
	.ascii	"Mar"
	.ascii	"Apr"
	.ascii	"May"
	.ascii	"Jun"
	.ascii	"Jul"
	.ascii	"Aug"
	.ascii	"Sep"
	.ascii	"Oct"
	.ascii	"Nov"
	.ascii	"Dec"
	.align	2, 0
.LC0:
	.ascii	"%.3s %.3s %.2d %.2d:%.2d:%.2d %d\n\000"
.text
	.align	2, 0
	.globl	asctime_r
	.type	 asctime_r,function
	.thumb_func
asctime_r:
	push	{r4, r5, lr}
	add	sp, sp, #-20
	add	r5, r1, #0
	ldr	r1, .L3
	ldr	r3, [r0, #24]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, .L3+4
	add	r2, r2, r3
	ldr	r4, [r0, #16]
	lsl	r3, r4, #1
	add	r3, r3, r4
	ldr	r4, .L3+8
	add	r3, r3, r4
	ldr	r4, [r0, #12]
	str	r4, [sp]
	ldr	r4, [r0, #8]
	str	r4, [sp, #4]
	ldr	r4, [r0, #4]
	str	r4, [sp, #8]
	ldr	r4, [r0]
	str	r4, [sp, #12]
	ldr	r0, [r0, #20]
	ldr	r4, .L3+12
	add	r0, r0, r4
	str	r0, [sp, #16]
	add	r0, r5, #0
	bl	sprintf
	add	r0, r5, #0
	add	sp, sp, #20
	pop	{r4, r5, pc}
.L4:
	.align	2, 0
.L3:
	.word	.LC0
	.word	day_name.3
	.word	mon_name.4
	.word	1900
.Lfe1:
	.size	 asctime_r,.Lfe1-asctime_r
.text
	.align	2, 0
