@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	clock
	.type	 clock,function
	.thumb_func
clock:
	push	{lr}
	add	sp, sp, #-16
	ldr	r0, .L4
	ldr	r0, [r0]
	mov	r1, sp
	bl	_times_r
	add	r1, r0, #0
	mov	r0, #1
	neg	r0, r0
	cmp	r1, r0
	beq	.L3	@cond_branch
	ldr	r0, [sp]
	ldr	r1, [sp, #4]
	add	r0, r0, r1
	ldr	r1, [sp, #8]
	add	r0, r0, r1
	ldr	r1, [sp, #12]
	add	r1, r0, r1
.L3:
	add	r0, r1, #0
	add	sp, sp, #16
	pop	{pc}
.L5:
	.align	2, 0
.L4:
	.word	_impure_ptr
.Lfe1:
	.size	 clock,.Lfe1-clock
.text
	.align	2, 0
