@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	ctime_r
	.type	 ctime_r,function
	.thumb_func
ctime_r:
	push	{r4, lr}
	add	sp, sp, #-36
	add	r4, r1, #0
	mov	r1, sp
	bl	localtime_r
	add	r1, r4, #0
	bl	asctime_r
	add	sp, sp, #36
	pop	{r4, pc}
.Lfe1:
	.size	 ctime_r,.Lfe1-ctime_r
.text
	.align	2, 0
