@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	difftime
	.type	 difftime,function
	.thumb_func
difftime:
	push	{r4, r5, r6, lr}
	add	r6, r1, #0
	bl	__floatsidf
	add	r5, r1, #0
	add	r4, r0, #0
	add	r0, r6, #0
	bl	__floatsidf
	add	r3, r1, #0
	add	r2, r0, #0
	add	r1, r5, #0
	add	r0, r4, #0
	bl	__subdf3
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 difftime,.Lfe1-difftime
.text
	.align	2, 0
