@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	gmtime_r
	.type	 gmtime_r,function
	.thumb_func
gmtime_r:
	push	{lr}
	add	sp, sp, #-4
	ldr	r0, [r0]
	str	r0, [sp]
	mov	r0, sp
	bl	localtime_r
	add	sp, sp, #4
	pop	{pc}
.Lfe1:
	.size	 gmtime_r,.Lfe1-gmtime_r
.text
	.align	2, 0
