@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	gmtime
	.type	 gmtime,function
	.thumb_func
gmtime:
	push	{lr}
	add	sp, sp, #-4
	ldr	r0, [r0]
	str	r0, [sp]
	mov	r0, sp
	bl	localtime
	add	sp, sp, #4
	pop	{pc}
.Lfe1:
	.size	 gmtime,.Lfe1-gmtime
.text
	.align	2, 0
