@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	time
	.type	 time,function
	.thumb_func
time:
	push	{r4, lr}
	add	sp, sp, #-8
	add	r4, r0, #0
	ldr	r0, .L6
	ldr	r0, [r0]
	mov	r1, sp
	mov	r2, #0
	bl	_gettimeofday_r
	cmp	r0, #0
	blt	.L3	@cond_branch
	ldr	r0, [sp]
	cmp	r4, #0
	beq	.L5	@cond_branch
	str	r0, [r4]
	b	.L5
.L7:
	.align	2, 0
.L6:
	.word	_impure_ptr
.L3:
	mov	r0, #1
	neg	r0, r0
.L5:
	add	sp, sp, #8
	pop	{r4, pc}
.Lfe1:
	.size	 time,.Lfe1-time
.text
	.align	2, 0
