name: Build ROM

on:
  push:
    branches: [ "progress" ]
  pull_request:
    branches: [ "progress" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Configure Git options
        run: |
          git config --global core.longpaths true
          git config --global core.symlinks false
=======
      - name: Configure Git for long paths and symlinks
        run: |
          git config --global core.longpaths true
>>>>>>> 0b7ac2e90f821747e4030dd1d4ca84d88f420893

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpng-dev liblzma-dev pkg-config

      - name: Build tools and ROM
        run: |
          make CFLAGS="-std=gnu89 -Wno-error"
          make

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-crystaldust-rom
          path: |
            *.gba
<<<<<<< HEAD
            *.map
=======
            *.map
>>>>>>> 0b7ac2e90f821747e4030dd1d4ca84d88f420893
